// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"

	dt "github.com/helixfhir/gofhir/r4/datatypes"
)

// Account A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc.
type Account struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Account"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Unique identifier used to reference the account.  Might or might not be intended for human use (e.g. credit card number).
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status Indicates whether the account is presently used/usable or not.
	Status *string `json:"status,omitempty"`
	// Coverage The party(s) that are responsible for covering the payment of this account, and what order should they be applied to the account.
	Coverage []AccountCoverage `json:"coverage,omitempty"`
	// Description Provides additional information about what the account tracks and how it is used.
	Description *string `json:"description,omitempty"`
	// Guarantor The parties responsible for balancing the account if other payment options fall short.
	Guarantor []AccountGuarantor `json:"guarantor,omitempty"`
	// Name Name used for the account when displaying it to humans in reports, etc.
	Name *string `json:"name,omitempty"`
	// Owner Indicates the service area, hospital, department, etc. with responsibility for managing the Account.
	Owner *dt.Reference `json:"owner,omitempty"`
	// PartOf Reference to a parent Account.
	PartOf *dt.Reference `json:"partOf,omitempty"`
	// ServicePeriod The date range of services associated with this account.
	ServicePeriod *dt.Period `json:"servicePeriod,omitempty"`
	// Subject Identifies the entity which incurs the expenses. While the immediate recipients of services or goods might be entities related to the subject, the expenses were ultimately incurred by the subject o...
	Subject []dt.Reference `json:"subject,omitempty"`
	// Type Categorizes the account for reporting and searching purposes.
	Type *dt.CodeableConcept `json:"type,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for Account.
func (r Account) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Account"
	type Alias Account
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON implements the json.Unmarshaler interface for Account.
func (r *Account) UnmarshalJSON(data []byte) error {
	type Alias Account
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Account(alias)
	return nil
}

// AccountBuilder provides a fluent API for constructing Account resources.
type AccountBuilder struct {
	resource Account
}

// NewAccount creates a new AccountBuilder for building a Account resource.
func NewAccount() *AccountBuilder {
	return &AccountBuilder{resource: Account{ResourceType: "Account"}}
}

// WithId sets the id field.
func (b *AccountBuilder) WithId(v dt.ID) *AccountBuilder {
	b.resource.Id = &v
	return b
}

// WithMeta sets the meta field.
func (b *AccountBuilder) WithMeta(v dt.Meta) *AccountBuilder {
	b.resource.Meta = &v
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *AccountBuilder) WithImplicitRules(v dt.URI) *AccountBuilder {
	b.resource.ImplicitRules = &v
	return b
}

// WithLanguage sets the language field.
func (b *AccountBuilder) WithLanguage(v dt.Code) *AccountBuilder {
	b.resource.Language = &v
	return b
}

// WithText sets the text field.
func (b *AccountBuilder) WithText(v dt.Narrative) *AccountBuilder {
	b.resource.Text = &v
	return b
}

// WithContained adds an item to the contained field.
func (b *AccountBuilder) WithContained(v json.RawMessage) *AccountBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	return b
}

// WithExtension adds an item to the extension field.
func (b *AccountBuilder) WithExtension(v dt.Extension) *AccountBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *AccountBuilder) WithModifierExtension(v dt.Extension) *AccountBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *AccountBuilder) WithIdentifier(v dt.Identifier) *AccountBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	return b
}

// WithStatus sets the status field.
func (b *AccountBuilder) WithStatus(v string) *AccountBuilder {
	b.resource.Status = &v
	return b
}

// WithCoverage adds an item to the coverage field.
func (b *AccountBuilder) WithCoverage(v AccountCoverage) *AccountBuilder {
	b.resource.Coverage = append(b.resource.Coverage, v)
	return b
}

// WithDescription sets the description field.
func (b *AccountBuilder) WithDescription(v string) *AccountBuilder {
	b.resource.Description = &v
	return b
}

// WithGuarantor adds an item to the guarantor field.
func (b *AccountBuilder) WithGuarantor(v AccountGuarantor) *AccountBuilder {
	b.resource.Guarantor = append(b.resource.Guarantor, v)
	return b
}

// WithName sets the name field.
func (b *AccountBuilder) WithName(v string) *AccountBuilder {
	b.resource.Name = &v
	return b
}

// WithOwner sets the owner field.
func (b *AccountBuilder) WithOwner(v dt.Reference) *AccountBuilder {
	b.resource.Owner = &v
	return b
}

// WithPartOf sets the partOf field.
func (b *AccountBuilder) WithPartOf(v dt.Reference) *AccountBuilder {
	b.resource.PartOf = &v
	return b
}

// WithServicePeriod sets the servicePeriod field.
func (b *AccountBuilder) WithServicePeriod(v dt.Period) *AccountBuilder {
	b.resource.ServicePeriod = &v
	return b
}

// WithSubject adds an item to the subject field.
func (b *AccountBuilder) WithSubject(v dt.Reference) *AccountBuilder {
	b.resource.Subject = append(b.resource.Subject, v)
	return b
}

// WithType sets the type field.
func (b *AccountBuilder) WithType(v dt.CodeableConcept) *AccountBuilder {
	b.resource.Type = &v
	return b
}

// Build returns the constructed Account. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *AccountBuilder) Build() (*Account, error) {
	r := b.resource
	return &r, nil
}

// AccountCoverage A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc.
type AccountCoverage struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Coverage The party(s) that contribute to payment (or part of) of the charges applied to this account (including self-pay).  A coverage may only be responsible for specific types of charges, and the sequence...
	Coverage dt.Reference `json:"coverage"`
	// Priority The priority of the coverage in the context of this account.
	Priority *uint32 `json:"priority,omitempty"`
}

// AccountGuarantor A financial tool for tracking value accrued for a particular purpose.  In the healthcare field, used to track charges for a patient, cost centers, etc.
type AccountGuarantor struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// OnHold A guarantor may be placed on credit hold or otherwise have their role temporarily suspended.
	OnHold *bool `json:"onHold,omitempty"`
	// Party The entity who is responsible.
	Party dt.Reference `json:"party"`
	// Period The timeframe during which the guarantor accepts responsibility for the account.
	Period *dt.Period `json:"period,omitempty"`
}
