// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// Appointment A booking of a healthcare event among patient(s), practitioner(s), related person(s) and/or device(s) for a specific date/time. This may result in one or more Encounter(s).
type Appointment struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Appointment"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier This records identifiers associated with this appointment concern that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropr...
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status The overall status of the Appointment. Each of the participants has their own participation status which indicates their involvement in the process, however this status indicates the shared status.
	Status *AppointmentStatus `json:"status,omitempty"`
	// StatusElement contains element extensions for status.
	StatusElement *dt.Element `json:"_status,omitempty"`
	// AppointmentType The style of appointment or patient that has been booked in the slot (not service type).
	AppointmentType *dt.CodeableConcept `json:"appointmentType,omitempty"`
	// BasedOn The service request this appointment is allocated to assess (e.g. incoming referral or procedure request).
	BasedOn []dt.Reference `json:"basedOn,omitempty"`
	// CancelationReason The coded reason for the appointment being cancelled. This is often used in reporting/billing/futher processing to determine if further actions are required, or specific fees apply.
	CancelationReason *dt.CodeableConcept `json:"cancelationReason,omitempty"`
	// Comment Additional comments about the appointment.
	Comment *string `json:"comment,omitempty"`
	// CommentElement contains element extensions for comment.
	CommentElement *dt.Element `json:"_comment,omitempty"`
	// Created The date that this appointment was initially created. This could be different to the meta.lastModified value on the initial entry, as this could have been before the resource was created on the FHI...
	Created *dt.DateTime `json:"created,omitempty"`
	// CreatedElement contains element extensions for created.
	CreatedElement *dt.Element `json:"_created,omitempty"`
	// Description The brief description of the appointment as would be shown on a subject line in a meeting request, or appointment list. Detailed or expanded information should be put in the comment field.
	Description *string `json:"description,omitempty"`
	// DescriptionElement contains element extensions for description.
	DescriptionElement *dt.Element `json:"_description,omitempty"`
	// End Date/Time that the appointment is to conclude.
	End *dt.Instant `json:"end,omitempty"`
	// EndElement contains element extensions for end.
	EndElement *dt.Element `json:"_end,omitempty"`
	// MinutesDuration Number of minutes that the appointment is to take. This can be less than the duration between the start and end times.  For example, where the actual time of appointment is only an estimate or if a...
	MinutesDuration *uint32 `json:"minutesDuration,omitempty"`
	// MinutesDurationElement contains element extensions for minutesDuration.
	MinutesDurationElement *dt.Element `json:"_minutesDuration,omitempty"`
	// Participant List of participants involved in the appointment.
	Participant []AppointmentParticipant `json:"participant,omitempty"`
	// PatientInstruction While Appointment.comment contains information for internal use, Appointment.patientInstructions is used to capture patient facing information about the Appointment (e.g. please bring your referral...
	PatientInstruction *string `json:"patientInstruction,omitempty"`
	// PatientInstructionElement contains element extensions for patientInstruction.
	PatientInstructionElement *dt.Element `json:"_patientInstruction,omitempty"`
	// Priority The priority of the appointment. Can be used to make informed decisions if needing to re-prioritize appointments. (The iCal Standard specifies 0 as undefined, 1 as highest, 9 as lowest priority).
	Priority *uint32 `json:"priority,omitempty"`
	// PriorityElement contains element extensions for priority.
	PriorityElement *dt.Element `json:"_priority,omitempty"`
	// ReasonCode The coded reason that this appointment is being scheduled. This is more clinical than administrative.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonReference Reason the appointment has been scheduled to take place, as specified using information from another resource. When the patient arrives and the encounter begins it may be used as the admission diag...
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// RequestedPeriod A set of date ranges (potentially including times) that the appointment is preferred to be scheduled within.  The duration (usually in minutes) could also be provided to indicate the length of the ...
	RequestedPeriod []dt.Period `json:"requestedPeriod,omitempty"`
	// ServiceCategory A broad categorization of the service that is to be performed during this appointment.
	ServiceCategory []dt.CodeableConcept `json:"serviceCategory,omitempty"`
	// ServiceType The specific service that is to be performed during this appointment.
	ServiceType []dt.CodeableConcept `json:"serviceType,omitempty"`
	// Slot The slots from the participants' schedules that will be filled by the appointment.
	Slot []dt.Reference `json:"slot,omitempty"`
	// Specialty The specialty of a practitioner that would be required to perform the service requested in this appointment.
	Specialty []dt.CodeableConcept `json:"specialty,omitempty"`
	// Start Date/Time that the appointment is to take place.
	Start *dt.Instant `json:"start,omitempty"`
	// StartElement contains element extensions for start.
	StartElement *dt.Element `json:"_start,omitempty"`
	// SupportingInformation Additional information to support the appointment provided when making the appointment.
	SupportingInformation []dt.Reference `json:"supportingInformation,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for Appointment.
func (r Appointment) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Appointment"
	type Alias Appointment
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	if len(r.Extra) == 0 {
		return data, nil
	}
	// Splice Extra fields into JSON output
	var extra []byte
	for k, v := range r.Extra {
		key, _ := json.Marshal(k)
		extra = append(extra, ',')
		extra = append(extra, key...)
		extra = append(extra, ':')
		extra = append(extra, v...)
	}
	// Insert before final '}'
	result := make([]byte, 0, len(data)+len(extra))
	result = append(result, data[:len(data)-1]...)
	result = append(result, extra...)
	result = append(result, '}')
	return result, nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Appointment.
func (r *Appointment) UnmarshalJSON(data []byte) error {
	type Alias Appointment
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Appointment(alias)
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_appointmentType", "_basedOn", "_cancelationReason", "_comment", "_contained", "_created", "_description", "_end", "_extension", "_id", "_identifier", "_implicitRules", "_language", "_meta", "_minutesDuration", "_modifierExtension", "_participant", "_patientInstruction", "_priority", "_reasonCode", "_reasonReference", "_requestedPeriod", "_serviceCategory", "_serviceType", "_slot", "_specialty", "_start", "_status", "_supportingInformation", "_text", "appointmentType", "basedOn", "cancelationReason", "comment", "contained", "created", "description", "end", "extension", "id", "identifier", "implicitRules", "language", "meta", "minutesDuration", "modifierExtension", "participant", "patientInstruction", "priority", "reasonCode", "reasonReference", "requestedPeriod", "resourceType", "serviceCategory", "serviceType", "slot", "specialty", "start", "status", "supportingInformation", "text":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// AppointmentBuilder provides a fluent API for constructing Appointment resources.
type AppointmentBuilder struct {
	resource  Appointment
	fieldsSet map[string]bool
}

// NewAppointment creates a new AppointmentBuilder for building a Appointment resource.
func NewAppointment() *AppointmentBuilder {
	return &AppointmentBuilder{resource: Appointment{ResourceType: "Appointment"}, fieldsSet: make(map[string]bool)}
}

// WithId sets the id field.
func (b *AppointmentBuilder) WithId(v dt.ID) *AppointmentBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *AppointmentBuilder) WithMeta(v dt.Meta) *AppointmentBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *AppointmentBuilder) WithImplicitRules(v dt.URI) *AppointmentBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *AppointmentBuilder) WithLanguage(v dt.Code) *AppointmentBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *AppointmentBuilder) WithText(v dt.Narrative) *AppointmentBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *AppointmentBuilder) WithContained(v json.RawMessage) *AppointmentBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *AppointmentBuilder) WithExtension(v dt.Extension) *AppointmentBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *AppointmentBuilder) WithModifierExtension(v dt.Extension) *AppointmentBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *AppointmentBuilder) WithIdentifier(v dt.Identifier) *AppointmentBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	b.fieldsSet["identifier"] = true
	return b
}

// WithStatus sets the status field.
func (b *AppointmentBuilder) WithStatus(v AppointmentStatus) *AppointmentBuilder {
	b.resource.Status = &v
	b.fieldsSet["status"] = true
	return b
}

// WithAppointmentType sets the appointmentType field.
func (b *AppointmentBuilder) WithAppointmentType(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.AppointmentType = &v
	b.fieldsSet["appointmentType"] = true
	return b
}

// WithBasedOn adds an item to the basedOn field.
func (b *AppointmentBuilder) WithBasedOn(v dt.Reference) *AppointmentBuilder {
	b.resource.BasedOn = append(b.resource.BasedOn, v)
	b.fieldsSet["basedOn"] = true
	return b
}

// WithCancelationReason sets the cancelationReason field.
func (b *AppointmentBuilder) WithCancelationReason(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.CancelationReason = &v
	b.fieldsSet["cancelationReason"] = true
	return b
}

// WithComment sets the comment field.
func (b *AppointmentBuilder) WithComment(v string) *AppointmentBuilder {
	b.resource.Comment = &v
	b.fieldsSet["comment"] = true
	return b
}

// WithCreated sets the created field.
func (b *AppointmentBuilder) WithCreated(v dt.DateTime) *AppointmentBuilder {
	b.resource.Created = &v
	b.fieldsSet["created"] = true
	return b
}

// WithDescription sets the description field.
func (b *AppointmentBuilder) WithDescription(v string) *AppointmentBuilder {
	b.resource.Description = &v
	b.fieldsSet["description"] = true
	return b
}

// WithEnd sets the end field.
func (b *AppointmentBuilder) WithEnd(v dt.Instant) *AppointmentBuilder {
	b.resource.End = &v
	b.fieldsSet["end"] = true
	return b
}

// WithMinutesDuration sets the minutesDuration field.
func (b *AppointmentBuilder) WithMinutesDuration(v uint32) *AppointmentBuilder {
	b.resource.MinutesDuration = &v
	b.fieldsSet["minutesDuration"] = true
	return b
}

// WithParticipant adds an item to the participant field.
func (b *AppointmentBuilder) WithParticipant(v AppointmentParticipant) *AppointmentBuilder {
	b.resource.Participant = append(b.resource.Participant, v)
	b.fieldsSet["participant"] = true
	return b
}

// WithPatientInstruction sets the patientInstruction field.
func (b *AppointmentBuilder) WithPatientInstruction(v string) *AppointmentBuilder {
	b.resource.PatientInstruction = &v
	b.fieldsSet["patientInstruction"] = true
	return b
}

// WithPriority sets the priority field.
func (b *AppointmentBuilder) WithPriority(v uint32) *AppointmentBuilder {
	b.resource.Priority = &v
	b.fieldsSet["priority"] = true
	return b
}

// WithReasonCode adds an item to the reasonCode field.
func (b *AppointmentBuilder) WithReasonCode(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ReasonCode = append(b.resource.ReasonCode, v)
	b.fieldsSet["reasonCode"] = true
	return b
}

// WithReasonReference adds an item to the reasonReference field.
func (b *AppointmentBuilder) WithReasonReference(v dt.Reference) *AppointmentBuilder {
	b.resource.ReasonReference = append(b.resource.ReasonReference, v)
	b.fieldsSet["reasonReference"] = true
	return b
}

// WithRequestedPeriod adds an item to the requestedPeriod field.
func (b *AppointmentBuilder) WithRequestedPeriod(v dt.Period) *AppointmentBuilder {
	b.resource.RequestedPeriod = append(b.resource.RequestedPeriod, v)
	b.fieldsSet["requestedPeriod"] = true
	return b
}

// WithServiceCategory adds an item to the serviceCategory field.
func (b *AppointmentBuilder) WithServiceCategory(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ServiceCategory = append(b.resource.ServiceCategory, v)
	b.fieldsSet["serviceCategory"] = true
	return b
}

// WithServiceType adds an item to the serviceType field.
func (b *AppointmentBuilder) WithServiceType(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ServiceType = append(b.resource.ServiceType, v)
	b.fieldsSet["serviceType"] = true
	return b
}

// WithSlot adds an item to the slot field.
func (b *AppointmentBuilder) WithSlot(v dt.Reference) *AppointmentBuilder {
	b.resource.Slot = append(b.resource.Slot, v)
	b.fieldsSet["slot"] = true
	return b
}

// WithSpecialty adds an item to the specialty field.
func (b *AppointmentBuilder) WithSpecialty(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.Specialty = append(b.resource.Specialty, v)
	b.fieldsSet["specialty"] = true
	return b
}

// WithStart sets the start field.
func (b *AppointmentBuilder) WithStart(v dt.Instant) *AppointmentBuilder {
	b.resource.Start = &v
	b.fieldsSet["start"] = true
	return b
}

// WithSupportingInformation adds an item to the supportingInformation field.
func (b *AppointmentBuilder) WithSupportingInformation(v dt.Reference) *AppointmentBuilder {
	b.resource.SupportingInformation = append(b.resource.SupportingInformation, v)
	b.fieldsSet["supportingInformation"] = true
	return b
}

// Build returns the constructed Appointment. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *AppointmentBuilder) Build() (*Appointment, error) {
	var missing []string
	if !b.fieldsSet["participant"] {
		missing = append(missing, "participant")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("Appointment: required fields missing: %v", missing)
	}
	r := b.resource
	return &r, nil
}

// AppointmentParticipant A booking of a healthcare event among patient(s), practitioner(s), related person(s) and/or device(s) for a specific date/time. This may result in one or more Encounter(s).
type AppointmentParticipant struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Status Participation status of the actor.
	Status *AppointmentParticipantStatus `json:"status,omitempty"`
	// StatusElement contains element extensions for status.
	StatusElement *dt.Element `json:"_status,omitempty"`
	// Actor A Person, Location/HealthcareService or Device that is participating in the appointment.
	Actor *dt.Reference `json:"actor,omitempty"`
	// Period Participation period of the actor.
	Period *dt.Period `json:"period,omitempty"`
	// Required Whether this participant is required to be present at the meeting. This covers a use-case where two doctors need to meet to discuss the results for a specific patient, and the patient is not requir...
	Required *AppointmentParticipantRequired `json:"required,omitempty"`
	// RequiredElement contains element extensions for required.
	RequiredElement *dt.Element `json:"_required,omitempty"`
	// Type Role of participant in the appointment.
	Type []dt.CodeableConcept `json:"type,omitempty"`
}

// GetId returns the id field value, or the zero value if nil.
func (r *Appointment) GetId() dt.ID {
	if r.Id != nil {
		return *r.Id
	}
	var zero dt.ID
	return zero
}

// GetMeta returns the meta field value, or the zero value if nil.
func (r *Appointment) GetMeta() dt.Meta {
	if r.Meta != nil {
		return *r.Meta
	}
	var zero dt.Meta
	return zero
}

// GetImplicitRules returns the implicitRules field value, or the zero value if nil.
func (r *Appointment) GetImplicitRules() dt.URI {
	if r.ImplicitRules != nil {
		return *r.ImplicitRules
	}
	var zero dt.URI
	return zero
}

// GetLanguage returns the language field value, or the zero value if nil.
func (r *Appointment) GetLanguage() dt.Code {
	if r.Language != nil {
		return *r.Language
	}
	var zero dt.Code
	return zero
}

// GetText returns the text field value, or the zero value if nil.
func (r *Appointment) GetText() dt.Narrative {
	if r.Text != nil {
		return *r.Text
	}
	var zero dt.Narrative
	return zero
}

// GetContained returns the contained field value, or an empty slice if nil.
func (r *Appointment) GetContained() []json.RawMessage {
	if r.Contained != nil {
		return r.Contained
	}
	return nil
}

// GetExtension returns the extension field value, or an empty slice if nil.
func (r *Appointment) GetExtension() []dt.Extension {
	if r.Extension != nil {
		return r.Extension
	}
	return nil
}

// GetModifierExtension returns the modifierExtension field value, or an empty slice if nil.
func (r *Appointment) GetModifierExtension() []dt.Extension {
	if r.ModifierExtension != nil {
		return r.ModifierExtension
	}
	return nil
}

// GetIdentifier returns the identifier field value, or an empty slice if nil.
func (r *Appointment) GetIdentifier() []dt.Identifier {
	if r.Identifier != nil {
		return r.Identifier
	}
	return nil
}

// GetStatus returns the status field value, or the zero value if nil.
func (r *Appointment) GetStatus() AppointmentStatus {
	if r.Status != nil {
		return *r.Status
	}
	var zero AppointmentStatus
	return zero
}

// GetAppointmentType returns the appointmentType field value, or the zero value if nil.
func (r *Appointment) GetAppointmentType() dt.CodeableConcept {
	if r.AppointmentType != nil {
		return *r.AppointmentType
	}
	var zero dt.CodeableConcept
	return zero
}

// GetBasedOn returns the basedOn field value, or an empty slice if nil.
func (r *Appointment) GetBasedOn() []dt.Reference {
	if r.BasedOn != nil {
		return r.BasedOn
	}
	return nil
}

// GetCancelationReason returns the cancelationReason field value, or the zero value if nil.
func (r *Appointment) GetCancelationReason() dt.CodeableConcept {
	if r.CancelationReason != nil {
		return *r.CancelationReason
	}
	var zero dt.CodeableConcept
	return zero
}

// GetComment returns the comment field value, or the zero value if nil.
func (r *Appointment) GetComment() string {
	if r.Comment != nil {
		return *r.Comment
	}
	var zero string
	return zero
}

// GetCreated returns the created field value, or the zero value if nil.
func (r *Appointment) GetCreated() dt.DateTime {
	if r.Created != nil {
		return *r.Created
	}
	var zero dt.DateTime
	return zero
}

// GetDescription returns the description field value, or the zero value if nil.
func (r *Appointment) GetDescription() string {
	if r.Description != nil {
		return *r.Description
	}
	var zero string
	return zero
}

// GetEnd returns the end field value, or the zero value if nil.
func (r *Appointment) GetEnd() dt.Instant {
	if r.End != nil {
		return *r.End
	}
	var zero dt.Instant
	return zero
}

// GetMinutesDuration returns the minutesDuration field value, or the zero value if nil.
func (r *Appointment) GetMinutesDuration() uint32 {
	if r.MinutesDuration != nil {
		return *r.MinutesDuration
	}
	var zero uint32
	return zero
}

// GetParticipant returns the participant field value, or an empty slice if nil.
func (r *Appointment) GetParticipant() []AppointmentParticipant {
	if r.Participant != nil {
		return r.Participant
	}
	return nil
}

// GetPatientInstruction returns the patientInstruction field value, or the zero value if nil.
func (r *Appointment) GetPatientInstruction() string {
	if r.PatientInstruction != nil {
		return *r.PatientInstruction
	}
	var zero string
	return zero
}

// GetPriority returns the priority field value, or the zero value if nil.
func (r *Appointment) GetPriority() uint32 {
	if r.Priority != nil {
		return *r.Priority
	}
	var zero uint32
	return zero
}

// GetReasonCode returns the reasonCode field value, or an empty slice if nil.
func (r *Appointment) GetReasonCode() []dt.CodeableConcept {
	if r.ReasonCode != nil {
		return r.ReasonCode
	}
	return nil
}

// GetReasonReference returns the reasonReference field value, or an empty slice if nil.
func (r *Appointment) GetReasonReference() []dt.Reference {
	if r.ReasonReference != nil {
		return r.ReasonReference
	}
	return nil
}

// GetRequestedPeriod returns the requestedPeriod field value, or an empty slice if nil.
func (r *Appointment) GetRequestedPeriod() []dt.Period {
	if r.RequestedPeriod != nil {
		return r.RequestedPeriod
	}
	return nil
}

// GetServiceCategory returns the serviceCategory field value, or an empty slice if nil.
func (r *Appointment) GetServiceCategory() []dt.CodeableConcept {
	if r.ServiceCategory != nil {
		return r.ServiceCategory
	}
	return nil
}

// GetServiceType returns the serviceType field value, or an empty slice if nil.
func (r *Appointment) GetServiceType() []dt.CodeableConcept {
	if r.ServiceType != nil {
		return r.ServiceType
	}
	return nil
}

// GetSlot returns the slot field value, or an empty slice if nil.
func (r *Appointment) GetSlot() []dt.Reference {
	if r.Slot != nil {
		return r.Slot
	}
	return nil
}

// GetSpecialty returns the specialty field value, or an empty slice if nil.
func (r *Appointment) GetSpecialty() []dt.CodeableConcept {
	if r.Specialty != nil {
		return r.Specialty
	}
	return nil
}

// GetStart returns the start field value, or the zero value if nil.
func (r *Appointment) GetStart() dt.Instant {
	if r.Start != nil {
		return *r.Start
	}
	var zero dt.Instant
	return zero
}

// GetSupportingInformation returns the supportingInformation field value, or an empty slice if nil.
func (r *Appointment) GetSupportingInformation() []dt.Reference {
	if r.SupportingInformation != nil {
		return r.SupportingInformation
	}
	return nil
}

// GetResourceType returns the FHIR resource type name.
func (r *Appointment) GetResourceType() string {
	return "Appointment"
}

// GetExtra returns unknown fields captured during JSON unmarshaling.
func (r *Appointment) GetExtra() map[string]json.RawMessage {
	return r.Extra
}
