// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/helixfhir/gofhir/r4/datatypes"
)

// Appointment A booking of a healthcare event among patient(s), practitioner(s), related person(s) and/or device(s) for a specific date/time. This may result in one or more Encounter(s).
type Appointment struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Appointment"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier This records identifiers associated with this appointment concern that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropr...
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status The overall status of the Appointment. Each of the participants has their own participation status which indicates their involvement in the process, however this status indicates the shared status.
	Status *string `json:"status,omitempty"`
	// AppointmentType The style of appointment or patient that has been booked in the slot (not service type).
	AppointmentType *dt.CodeableConcept `json:"appointmentType,omitempty"`
	// BasedOn The service request this appointment is allocated to assess (e.g. incoming referral or procedure request).
	BasedOn []dt.Reference `json:"basedOn,omitempty"`
	// CancelationReason The coded reason for the appointment being cancelled. This is often used in reporting/billing/futher processing to determine if further actions are required, or specific fees apply.
	CancelationReason *dt.CodeableConcept `json:"cancelationReason,omitempty"`
	// Comment Additional comments about the appointment.
	Comment *string `json:"comment,omitempty"`
	// Created The date that this appointment was initially created. This could be different to the meta.lastModified value on the initial entry, as this could have been before the resource was created on the FHI...
	Created *dt.DateTime `json:"created,omitempty"`
	// Description The brief description of the appointment as would be shown on a subject line in a meeting request, or appointment list. Detailed or expanded information should be put in the comment field.
	Description *string `json:"description,omitempty"`
	// End Date/Time that the appointment is to conclude.
	End *dt.Instant `json:"end,omitempty"`
	// MinutesDuration Number of minutes that the appointment is to take. This can be less than the duration between the start and end times.  For example, where the actual time of appointment is only an estimate or if a...
	MinutesDuration *uint32 `json:"minutesDuration,omitempty"`
	// Participant List of participants involved in the appointment.
	Participant []AppointmentParticipant `json:"participant,omitempty"`
	// PatientInstruction While Appointment.comment contains information for internal use, Appointment.patientInstructions is used to capture patient facing information about the Appointment (e.g. please bring your referral...
	PatientInstruction *string `json:"patientInstruction,omitempty"`
	// Priority The priority of the appointment. Can be used to make informed decisions if needing to re-prioritize appointments. (The iCal Standard specifies 0 as undefined, 1 as highest, 9 as lowest priority).
	Priority *uint32 `json:"priority,omitempty"`
	// ReasonCode The coded reason that this appointment is being scheduled. This is more clinical than administrative.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonReference Reason the appointment has been scheduled to take place, as specified using information from another resource. When the patient arrives and the encounter begins it may be used as the admission diag...
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// RequestedPeriod A set of date ranges (potentially including times) that the appointment is preferred to be scheduled within.  The duration (usually in minutes) could also be provided to indicate the length of the ...
	RequestedPeriod []dt.Period `json:"requestedPeriod,omitempty"`
	// ServiceCategory A broad categorization of the service that is to be performed during this appointment.
	ServiceCategory []dt.CodeableConcept `json:"serviceCategory,omitempty"`
	// ServiceType The specific service that is to be performed during this appointment.
	ServiceType []dt.CodeableConcept `json:"serviceType,omitempty"`
	// Slot The slots from the participants' schedules that will be filled by the appointment.
	Slot []dt.Reference `json:"slot,omitempty"`
	// Specialty The specialty of a practitioner that would be required to perform the service requested in this appointment.
	Specialty []dt.CodeableConcept `json:"specialty,omitempty"`
	// Start Date/Time that the appointment is to take place.
	Start *dt.Instant `json:"start,omitempty"`
	// SupportingInformation Additional information to support the appointment provided when making the appointment.
	SupportingInformation []dt.Reference `json:"supportingInformation,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for Appointment.
func (r Appointment) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Appointment"
	type Alias Appointment
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON implements the json.Unmarshaler interface for Appointment.
func (r *Appointment) UnmarshalJSON(data []byte) error {
	type Alias Appointment
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Appointment(alias)
	return nil
}

// AppointmentBuilder provides a fluent API for constructing Appointment resources.
type AppointmentBuilder struct {
	resource Appointment
}

// NewAppointment creates a new AppointmentBuilder for building a Appointment resource.
func NewAppointment() *AppointmentBuilder {
	return &AppointmentBuilder{resource: Appointment{ResourceType: "Appointment"}}
}

// WithId sets the id field.
func (b *AppointmentBuilder) WithId(v dt.ID) *AppointmentBuilder {
	b.resource.Id = &v
	return b
}

// WithMeta sets the meta field.
func (b *AppointmentBuilder) WithMeta(v dt.Meta) *AppointmentBuilder {
	b.resource.Meta = &v
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *AppointmentBuilder) WithImplicitRules(v dt.URI) *AppointmentBuilder {
	b.resource.ImplicitRules = &v
	return b
}

// WithLanguage sets the language field.
func (b *AppointmentBuilder) WithLanguage(v dt.Code) *AppointmentBuilder {
	b.resource.Language = &v
	return b
}

// WithText sets the text field.
func (b *AppointmentBuilder) WithText(v dt.Narrative) *AppointmentBuilder {
	b.resource.Text = &v
	return b
}

// WithContained adds an item to the contained field.
func (b *AppointmentBuilder) WithContained(v json.RawMessage) *AppointmentBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	return b
}

// WithExtension adds an item to the extension field.
func (b *AppointmentBuilder) WithExtension(v dt.Extension) *AppointmentBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *AppointmentBuilder) WithModifierExtension(v dt.Extension) *AppointmentBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *AppointmentBuilder) WithIdentifier(v dt.Identifier) *AppointmentBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	return b
}

// WithStatus sets the status field.
func (b *AppointmentBuilder) WithStatus(v string) *AppointmentBuilder {
	b.resource.Status = &v
	return b
}

// WithAppointmentType sets the appointmentType field.
func (b *AppointmentBuilder) WithAppointmentType(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.AppointmentType = &v
	return b
}

// WithBasedOn adds an item to the basedOn field.
func (b *AppointmentBuilder) WithBasedOn(v dt.Reference) *AppointmentBuilder {
	b.resource.BasedOn = append(b.resource.BasedOn, v)
	return b
}

// WithCancelationReason sets the cancelationReason field.
func (b *AppointmentBuilder) WithCancelationReason(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.CancelationReason = &v
	return b
}

// WithComment sets the comment field.
func (b *AppointmentBuilder) WithComment(v string) *AppointmentBuilder {
	b.resource.Comment = &v
	return b
}

// WithCreated sets the created field.
func (b *AppointmentBuilder) WithCreated(v dt.DateTime) *AppointmentBuilder {
	b.resource.Created = &v
	return b
}

// WithDescription sets the description field.
func (b *AppointmentBuilder) WithDescription(v string) *AppointmentBuilder {
	b.resource.Description = &v
	return b
}

// WithEnd sets the end field.
func (b *AppointmentBuilder) WithEnd(v dt.Instant) *AppointmentBuilder {
	b.resource.End = &v
	return b
}

// WithMinutesDuration sets the minutesDuration field.
func (b *AppointmentBuilder) WithMinutesDuration(v uint32) *AppointmentBuilder {
	b.resource.MinutesDuration = &v
	return b
}

// WithParticipant adds an item to the participant field.
func (b *AppointmentBuilder) WithParticipant(v AppointmentParticipant) *AppointmentBuilder {
	b.resource.Participant = append(b.resource.Participant, v)
	return b
}

// WithPatientInstruction sets the patientInstruction field.
func (b *AppointmentBuilder) WithPatientInstruction(v string) *AppointmentBuilder {
	b.resource.PatientInstruction = &v
	return b
}

// WithPriority sets the priority field.
func (b *AppointmentBuilder) WithPriority(v uint32) *AppointmentBuilder {
	b.resource.Priority = &v
	return b
}

// WithReasonCode adds an item to the reasonCode field.
func (b *AppointmentBuilder) WithReasonCode(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ReasonCode = append(b.resource.ReasonCode, v)
	return b
}

// WithReasonReference adds an item to the reasonReference field.
func (b *AppointmentBuilder) WithReasonReference(v dt.Reference) *AppointmentBuilder {
	b.resource.ReasonReference = append(b.resource.ReasonReference, v)
	return b
}

// WithRequestedPeriod adds an item to the requestedPeriod field.
func (b *AppointmentBuilder) WithRequestedPeriod(v dt.Period) *AppointmentBuilder {
	b.resource.RequestedPeriod = append(b.resource.RequestedPeriod, v)
	return b
}

// WithServiceCategory adds an item to the serviceCategory field.
func (b *AppointmentBuilder) WithServiceCategory(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ServiceCategory = append(b.resource.ServiceCategory, v)
	return b
}

// WithServiceType adds an item to the serviceType field.
func (b *AppointmentBuilder) WithServiceType(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.ServiceType = append(b.resource.ServiceType, v)
	return b
}

// WithSlot adds an item to the slot field.
func (b *AppointmentBuilder) WithSlot(v dt.Reference) *AppointmentBuilder {
	b.resource.Slot = append(b.resource.Slot, v)
	return b
}

// WithSpecialty adds an item to the specialty field.
func (b *AppointmentBuilder) WithSpecialty(v dt.CodeableConcept) *AppointmentBuilder {
	b.resource.Specialty = append(b.resource.Specialty, v)
	return b
}

// WithStart sets the start field.
func (b *AppointmentBuilder) WithStart(v dt.Instant) *AppointmentBuilder {
	b.resource.Start = &v
	return b
}

// WithSupportingInformation adds an item to the supportingInformation field.
func (b *AppointmentBuilder) WithSupportingInformation(v dt.Reference) *AppointmentBuilder {
	b.resource.SupportingInformation = append(b.resource.SupportingInformation, v)
	return b
}

// Build returns the constructed Appointment. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *AppointmentBuilder) Build() (*Appointment, error) {
	var missing []string
	if len(b.resource.Participant) == 0 {
		missing = append(missing, "participant")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("Appointment: required fields missing: %v", missing)
	}
	r := b.resource
	return &r, nil
}

// AppointmentParticipant A booking of a healthcare event among patient(s), practitioner(s), related person(s) and/or device(s) for a specific date/time. This may result in one or more Encounter(s).
type AppointmentParticipant struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Status Participation status of the actor.
	Status *string `json:"status,omitempty"`
	// Actor A Person, Location/HealthcareService or Device that is participating in the appointment.
	Actor *dt.Reference `json:"actor,omitempty"`
	// Period Participation period of the actor.
	Period *dt.Period `json:"period,omitempty"`
	// Required Whether this participant is required to be present at the meeting. This covers a use-case where two doctors need to meet to discuss the results for a specific patient, and the patient is not requir...
	Required *string `json:"required,omitempty"`
	// Type Role of participant in the appointment.
	Type []dt.CodeableConcept `json:"type,omitempty"`
}
