// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// BiologicallyDerivedProduct A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
type BiologicallyDerivedProduct struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "BiologicallyDerivedProduct"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier This records identifiers associated with this biologically derived product instance that are defined by business processes and/or used to refer to it when a direct URL reference to the resource its...
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status Whether the product is currently available.
	Status *BiologicallyDerivedProductStatus `json:"status,omitempty"`
	// StatusElement contains element extensions for status.
	StatusElement *dt.Element `json:"_status,omitempty"`
	// Collection How this product was collected.
	Collection *BiologicallyDerivedProductCollection `json:"collection,omitempty"`
	// Manipulation Any manipulation of product post-collection that is intended to alter the product.  For example a buffy-coat enrichment or CD8 reduction of Peripheral Blood Stem Cells to make it more suitable for ...
	Manipulation *BiologicallyDerivedProductManipulation `json:"manipulation,omitempty"`
	// Parent Parent product (if any).
	Parent []dt.Reference `json:"parent,omitempty"`
	// Processing Any processing of the product during collection that does not change the fundamental nature of the product. For example adding anti-coagulants during the collection of Peripheral Blood Stem Cells.
	Processing []BiologicallyDerivedProductProcessing `json:"processing,omitempty"`
	// Product Broad category of this product.
	Product *BiologicallyDerivedProductProduct `json:"-"` // polymorphic
	// Quantity Number of discrete units within this product.
	Quantity *int32 `json:"quantity,omitempty"`
	// QuantityElement contains element extensions for quantity.
	QuantityElement *dt.Element `json:"_quantity,omitempty"`
	// Request Procedure request to obtain this biologically derived product.
	Request []dt.Reference `json:"request,omitempty"`
	// Storage Product storage.
	Storage []BiologicallyDerivedProductStorage `json:"storage,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for BiologicallyDerivedProduct.
func (r BiologicallyDerivedProduct) MarshalJSON() ([]byte, error) {
	r.ResourceType = "BiologicallyDerivedProduct"
	type Alias BiologicallyDerivedProduct
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	// Collect additional fields to splice into JSON
	var extra []byte
	if r.Product != nil {
		vData, err := json.Marshal(r.Product)
		if err != nil {
			return nil, err
		}
		if len(vData) > 2 { // not empty {}
			extra = append(extra, ',')
			extra = append(extra, vData[1:len(vData)-1]...)
		}
	}
	for k, v := range r.Extra {
		key, _ := json.Marshal(k)
		extra = append(extra, ',')
		extra = append(extra, key...)
		extra = append(extra, ':')
		extra = append(extra, v...)
	}
	if len(extra) == 0 {
		return data, nil
	}
	result := make([]byte, 0, len(data)+len(extra))
	result = append(result, data[:len(data)-1]...)
	result = append(result, extra...)
	result = append(result, '}')
	return result, nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for BiologicallyDerivedProduct.
func (r *BiologicallyDerivedProduct) UnmarshalJSON(data []byte) error {
	type Alias BiologicallyDerivedProduct
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = BiologicallyDerivedProduct(alias)
	// Unmarshal polymorphic fields
	var productVal BiologicallyDerivedProductProduct
	if err := productVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if productVal.Category != nil || productVal.Code != nil {
		r.Product = &productVal
	}
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_collection", "_contained", "_extension", "_id", "_identifier", "_implicitRules", "_language", "_manipulation", "_meta", "_modifierExtension", "_parent", "_processing", "_productCategory", "_productCode", "_quantity", "_request", "_status", "_storage", "_text", "collection", "contained", "extension", "id", "identifier", "implicitRules", "language", "manipulation", "meta", "modifierExtension", "parent", "processing", "productCategory", "productCode", "quantity", "request", "resourceType", "status", "storage", "text":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// BiologicallyDerivedProductBuilder provides a fluent API for constructing BiologicallyDerivedProduct resources.
type BiologicallyDerivedProductBuilder struct {
	resource  BiologicallyDerivedProduct
	fieldsSet map[string]bool
}

// NewBiologicallyDerivedProduct creates a new BiologicallyDerivedProductBuilder for building a BiologicallyDerivedProduct resource.
func NewBiologicallyDerivedProduct() *BiologicallyDerivedProductBuilder {
	return &BiologicallyDerivedProductBuilder{resource: BiologicallyDerivedProduct{ResourceType: "BiologicallyDerivedProduct"}, fieldsSet: make(map[string]bool)}
}

// WithId sets the id field.
func (b *BiologicallyDerivedProductBuilder) WithId(v dt.ID) *BiologicallyDerivedProductBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *BiologicallyDerivedProductBuilder) WithMeta(v dt.Meta) *BiologicallyDerivedProductBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *BiologicallyDerivedProductBuilder) WithImplicitRules(v dt.URI) *BiologicallyDerivedProductBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *BiologicallyDerivedProductBuilder) WithLanguage(v dt.Code) *BiologicallyDerivedProductBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *BiologicallyDerivedProductBuilder) WithText(v dt.Narrative) *BiologicallyDerivedProductBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *BiologicallyDerivedProductBuilder) WithContained(v json.RawMessage) *BiologicallyDerivedProductBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *BiologicallyDerivedProductBuilder) WithExtension(v dt.Extension) *BiologicallyDerivedProductBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *BiologicallyDerivedProductBuilder) WithModifierExtension(v dt.Extension) *BiologicallyDerivedProductBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *BiologicallyDerivedProductBuilder) WithIdentifier(v dt.Identifier) *BiologicallyDerivedProductBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	b.fieldsSet["identifier"] = true
	return b
}

// WithStatus sets the status field.
func (b *BiologicallyDerivedProductBuilder) WithStatus(v BiologicallyDerivedProductStatus) *BiologicallyDerivedProductBuilder {
	b.resource.Status = &v
	b.fieldsSet["status"] = true
	return b
}

// WithCollection sets the collection field.
func (b *BiologicallyDerivedProductBuilder) WithCollection(v BiologicallyDerivedProductCollection) *BiologicallyDerivedProductBuilder {
	b.resource.Collection = &v
	b.fieldsSet["collection"] = true
	return b
}

// WithManipulation sets the manipulation field.
func (b *BiologicallyDerivedProductBuilder) WithManipulation(v BiologicallyDerivedProductManipulation) *BiologicallyDerivedProductBuilder {
	b.resource.Manipulation = &v
	b.fieldsSet["manipulation"] = true
	return b
}

// WithParent adds an item to the parent field.
func (b *BiologicallyDerivedProductBuilder) WithParent(v dt.Reference) *BiologicallyDerivedProductBuilder {
	b.resource.Parent = append(b.resource.Parent, v)
	b.fieldsSet["parent"] = true
	return b
}

// WithProcessing adds an item to the processing field.
func (b *BiologicallyDerivedProductBuilder) WithProcessing(v BiologicallyDerivedProductProcessing) *BiologicallyDerivedProductBuilder {
	b.resource.Processing = append(b.resource.Processing, v)
	b.fieldsSet["processing"] = true
	return b
}

// WithProductCategory sets the productCategory polymorphic field.
func (b *BiologicallyDerivedProductBuilder) WithProductCategory(v string) *BiologicallyDerivedProductBuilder {
	if b.resource.Product == nil {
		b.resource.Product = &BiologicallyDerivedProductProduct{}
	}
	b.resource.Product.Category = &v
	b.fieldsSet["product"] = true
	return b
}

// WithProductCode sets the productCode polymorphic field.
func (b *BiologicallyDerivedProductBuilder) WithProductCode(v dt.CodeableConcept) *BiologicallyDerivedProductBuilder {
	if b.resource.Product == nil {
		b.resource.Product = &BiologicallyDerivedProductProduct{}
	}
	b.resource.Product.Code = &v
	b.fieldsSet["product"] = true
	return b
}

// WithQuantity sets the quantity field.
func (b *BiologicallyDerivedProductBuilder) WithQuantity(v int32) *BiologicallyDerivedProductBuilder {
	b.resource.Quantity = &v
	b.fieldsSet["quantity"] = true
	return b
}

// WithRequest adds an item to the request field.
func (b *BiologicallyDerivedProductBuilder) WithRequest(v dt.Reference) *BiologicallyDerivedProductBuilder {
	b.resource.Request = append(b.resource.Request, v)
	b.fieldsSet["request"] = true
	return b
}

// WithStorage adds an item to the storage field.
func (b *BiologicallyDerivedProductBuilder) WithStorage(v BiologicallyDerivedProductStorage) *BiologicallyDerivedProductBuilder {
	b.resource.Storage = append(b.resource.Storage, v)
	b.fieldsSet["storage"] = true
	return b
}

// Build returns the constructed BiologicallyDerivedProduct. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *BiologicallyDerivedProductBuilder) Build() (*BiologicallyDerivedProduct, error) {
	r := b.resource
	return &r, nil
}

// BiologicallyDerivedProductCollection A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
type BiologicallyDerivedProductCollection struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// CollectedDateTime Time of product collection.
	CollectedDateTime *string `json:"collectedDateTime,omitempty"`
	// CollectedDateTimeElement contains element extensions for collectedDateTime.
	CollectedDateTimeElement *dt.Element `json:"_collectedDateTime,omitempty"`
	// CollectedPeriod Time of product collection.
	CollectedPeriod *dt.Period `json:"collectedPeriod,omitempty"`
	// Collector Healthcare professional who is performing the collection.
	Collector *dt.Reference `json:"collector,omitempty"`
	// Source The patient or entity, such as a hospital or vendor in the case of a processed/manipulated/manufactured product, providing the product.
	Source *dt.Reference `json:"source,omitempty"`
}

// BiologicallyDerivedProductManipulation A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
type BiologicallyDerivedProductManipulation struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Description Description of manipulation.
	Description *string `json:"description,omitempty"`
	// DescriptionElement contains element extensions for description.
	DescriptionElement *dt.Element `json:"_description,omitempty"`
	// TimeDateTime Time of manipulation.
	TimeDateTime *string `json:"timeDateTime,omitempty"`
	// TimeDateTimeElement contains element extensions for timeDateTime.
	TimeDateTimeElement *dt.Element `json:"_timeDateTime,omitempty"`
	// TimePeriod Time of manipulation.
	TimePeriod *dt.Period `json:"timePeriod,omitempty"`
}

// BiologicallyDerivedProductProcessing A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
type BiologicallyDerivedProductProcessing struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Additive Substance added during processing.
	Additive *dt.Reference `json:"additive,omitempty"`
	// Description Description of of processing.
	Description *string `json:"description,omitempty"`
	// DescriptionElement contains element extensions for description.
	DescriptionElement *dt.Element `json:"_description,omitempty"`
	// Procedure Procesing code.
	Procedure *dt.CodeableConcept `json:"procedure,omitempty"`
	// TimeDateTime Time of processing.
	TimeDateTime *string `json:"timeDateTime,omitempty"`
	// TimeDateTimeElement contains element extensions for timeDateTime.
	TimeDateTimeElement *dt.Element `json:"_timeDateTime,omitempty"`
	// TimePeriod Time of processing.
	TimePeriod *dt.Period `json:"timePeriod,omitempty"`
}

// BiologicallyDerivedProductStorage A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
type BiologicallyDerivedProductStorage struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Description Description of storage.
	Description *string `json:"description,omitempty"`
	// DescriptionElement contains element extensions for description.
	DescriptionElement *dt.Element `json:"_description,omitempty"`
	// Duration Storage timeperiod.
	Duration *dt.Period `json:"duration,omitempty"`
	// Scale Temperature scale used.
	Scale *BiologicallyDerivedProductStorageScale `json:"scale,omitempty"`
	// ScaleElement contains element extensions for scale.
	ScaleElement *dt.Element `json:"_scale,omitempty"`
	// Temperature Storage temperature.
	Temperature *dt.Decimal `json:"temperature,omitempty"`
	// TemperatureElement contains element extensions for temperature.
	TemperatureElement *dt.Element `json:"_temperature,omitempty"`
}

// BiologicallyDerivedProductProduct represents a polymorphic choice type in FHIR.
type BiologicallyDerivedProductProduct struct {
	Category *string             `json:"productCategory,omitempty"` // Broad category of this product.
	Code     *dt.CodeableConcept `json:"productCode,omitempty"`     // A code that identifies the kind of this biologically derived product (SNOMED Ctcode).
}

// MarshalJSON implements the json.Marshaler interface for BiologicallyDerivedProductProduct.
func (v BiologicallyDerivedProductProduct) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.Category != nil {
		m["productCategory"] = v.Category
	}
	if v.Code != nil {
		m["productCode"] = v.Code
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for BiologicallyDerivedProductProduct.
func (v *BiologicallyDerivedProductProduct) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["productCategory"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling productCategory: %w", err)
		}
		v.Category = &val
	}
	if d, ok := raw["productCode"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling productCode: %w", err)
		}
		v.Code = &val
	}
	return nil
}

// GetId returns the id field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetId() dt.ID {
	if r.Id != nil {
		return *r.Id
	}
	var zero dt.ID
	return zero
}

// GetMeta returns the meta field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetMeta() dt.Meta {
	if r.Meta != nil {
		return *r.Meta
	}
	var zero dt.Meta
	return zero
}

// GetImplicitRules returns the implicitRules field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetImplicitRules() dt.URI {
	if r.ImplicitRules != nil {
		return *r.ImplicitRules
	}
	var zero dt.URI
	return zero
}

// GetLanguage returns the language field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetLanguage() dt.Code {
	if r.Language != nil {
		return *r.Language
	}
	var zero dt.Code
	return zero
}

// GetText returns the text field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetText() dt.Narrative {
	if r.Text != nil {
		return *r.Text
	}
	var zero dt.Narrative
	return zero
}

// GetContained returns the contained field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetContained() []json.RawMessage {
	if r.Contained != nil {
		return r.Contained
	}
	return nil
}

// GetExtension returns the extension field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetExtension() []dt.Extension {
	if r.Extension != nil {
		return r.Extension
	}
	return nil
}

// GetModifierExtension returns the modifierExtension field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetModifierExtension() []dt.Extension {
	if r.ModifierExtension != nil {
		return r.ModifierExtension
	}
	return nil
}

// GetIdentifier returns the identifier field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetIdentifier() []dt.Identifier {
	if r.Identifier != nil {
		return r.Identifier
	}
	return nil
}

// GetStatus returns the status field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetStatus() BiologicallyDerivedProductStatus {
	if r.Status != nil {
		return *r.Status
	}
	var zero BiologicallyDerivedProductStatus
	return zero
}

// GetCollection returns the collection field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetCollection() BiologicallyDerivedProductCollection {
	if r.Collection != nil {
		return *r.Collection
	}
	var zero BiologicallyDerivedProductCollection
	return zero
}

// GetManipulation returns the manipulation field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetManipulation() BiologicallyDerivedProductManipulation {
	if r.Manipulation != nil {
		return *r.Manipulation
	}
	var zero BiologicallyDerivedProductManipulation
	return zero
}

// GetParent returns the parent field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetParent() []dt.Reference {
	if r.Parent != nil {
		return r.Parent
	}
	return nil
}

// GetProcessing returns the processing field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetProcessing() []BiologicallyDerivedProductProcessing {
	if r.Processing != nil {
		return r.Processing
	}
	return nil
}

// GetProduct returns the product field value, or a zero-value if nil.
func (r *BiologicallyDerivedProduct) GetProduct() BiologicallyDerivedProductProduct {
	if r.Product != nil {
		return *r.Product
	}
	return BiologicallyDerivedProductProduct{}
}

// GetQuantity returns the quantity field value, or the zero value if nil.
func (r *BiologicallyDerivedProduct) GetQuantity() int32 {
	if r.Quantity != nil {
		return *r.Quantity
	}
	var zero int32
	return zero
}

// GetRequest returns the request field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetRequest() []dt.Reference {
	if r.Request != nil {
		return r.Request
	}
	return nil
}

// GetStorage returns the storage field value, or an empty slice if nil.
func (r *BiologicallyDerivedProduct) GetStorage() []BiologicallyDerivedProductStorage {
	if r.Storage != nil {
		return r.Storage
	}
	return nil
}

// GetResourceType returns the FHIR resource type name.
func (r *BiologicallyDerivedProduct) GetResourceType() string {
	return "BiologicallyDerivedProduct"
}

// GetExtra returns unknown fields captured during JSON unmarshaling.
func (r *BiologicallyDerivedProduct) GetExtra() map[string]json.RawMessage {
	return r.Extra
}
