// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"

	dt "github.com/helixfhir/gofhir/r4/datatypes"
)

// Communication An occurrence of information being transmitted; e.g. an alert that was sent to a responsible provider, a public health agency that was notified about a reportable condition.
type Communication struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Communication"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Business identifiers assigned to this communication by the performer or other systems which remain constant as the resource is updated and propagates from server to server.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status The status of the transmission.
	Status *dt.Code `json:"status,omitempty"`
	// About Other resources that pertain to this communication and to which this communication should be associated.
	About []dt.Reference `json:"about,omitempty"`
	// BasedOn An order, proposal or plan fulfilled in whole or in part by this Communication.
	BasedOn []dt.Reference `json:"basedOn,omitempty"`
	// Category The type of message conveyed such as alert, notification, reminder, instruction, etc.
	Category []dt.CodeableConcept `json:"category,omitempty"`
	// Encounter The Encounter during which this Communication was created or to which the creation of this record is tightly associated.
	Encounter *dt.Reference `json:"encounter,omitempty"`
	// InResponseTo Prior communication that this communication is in response to.
	InResponseTo []dt.Reference `json:"inResponseTo,omitempty"`
	// InstantiatesCanonical The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.
	InstantiatesCanonical []dt.Canonical `json:"instantiatesCanonical,omitempty"`
	// InstantiatesUri The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this Communication.
	InstantiatesUri []dt.URI `json:"instantiatesUri,omitempty"`
	// Medium A channel that was used for this communication (e.g. email, fax).
	Medium []dt.CodeableConcept `json:"medium,omitempty"`
	// Note Additional notes or commentary about the communication by the sender, receiver or other interested parties.
	Note []dt.Annotation `json:"note,omitempty"`
	// PartOf Part of this action.
	PartOf []dt.Reference `json:"partOf,omitempty"`
	// Payload Text, attachment(s), or resource(s) that was communicated to the recipient.
	Payload []CommunicationPayload `json:"payload,omitempty"`
	// Priority Characterizes how quickly the planned or in progress communication must be addressed. Includes concepts such as stat, urgent, routine.
	Priority *dt.Code `json:"priority,omitempty"`
	// ReasonCode The reason or justification for the communication.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonReference Indicates another resource whose existence justifies this communication.
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// Received The time when this communication arrived at the destination.
	Received *dt.DateTime `json:"received,omitempty"`
	// Recipient The entity (e.g. person, organization, clinical information system, care team or device) which was the target of the communication. If receipts need to be tracked by an individual, a separate resou...
	Recipient []dt.Reference `json:"recipient,omitempty"`
	// Sender The entity (e.g. person, organization, clinical information system, or device) which was the source of the communication.
	Sender *dt.Reference `json:"sender,omitempty"`
	// Sent The time when this communication was sent.
	Sent *dt.DateTime `json:"sent,omitempty"`
	// StatusReason Captures the reason for the current state of the Communication.
	StatusReason *dt.CodeableConcept `json:"statusReason,omitempty"`
	// Subject The patient or group that was the focus of this communication.
	Subject *dt.Reference `json:"subject,omitempty"`
	// Topic Description of the purpose/content, similar to a subject line in an email.
	Topic *dt.CodeableConcept `json:"topic,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for Communication.
func (r Communication) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Communication"
	type Alias Communication
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON implements the json.Unmarshaler interface for Communication.
func (r *Communication) UnmarshalJSON(data []byte) error {
	type Alias Communication
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Communication(alias)
	return nil
}

// CommunicationBuilder provides a fluent API for constructing Communication resources.
type CommunicationBuilder struct {
	resource Communication
}

// NewCommunication creates a new CommunicationBuilder for building a Communication resource.
func NewCommunication() *CommunicationBuilder {
	return &CommunicationBuilder{resource: Communication{ResourceType: "Communication"}}
}

// WithId sets the id field.
func (b *CommunicationBuilder) WithId(v dt.ID) *CommunicationBuilder {
	b.resource.Id = &v
	return b
}

// WithMeta sets the meta field.
func (b *CommunicationBuilder) WithMeta(v dt.Meta) *CommunicationBuilder {
	b.resource.Meta = &v
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *CommunicationBuilder) WithImplicitRules(v dt.URI) *CommunicationBuilder {
	b.resource.ImplicitRules = &v
	return b
}

// WithLanguage sets the language field.
func (b *CommunicationBuilder) WithLanguage(v dt.Code) *CommunicationBuilder {
	b.resource.Language = &v
	return b
}

// WithText sets the text field.
func (b *CommunicationBuilder) WithText(v dt.Narrative) *CommunicationBuilder {
	b.resource.Text = &v
	return b
}

// WithContained adds an item to the contained field.
func (b *CommunicationBuilder) WithContained(v json.RawMessage) *CommunicationBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	return b
}

// WithExtension adds an item to the extension field.
func (b *CommunicationBuilder) WithExtension(v dt.Extension) *CommunicationBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *CommunicationBuilder) WithModifierExtension(v dt.Extension) *CommunicationBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *CommunicationBuilder) WithIdentifier(v dt.Identifier) *CommunicationBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	return b
}

// WithStatus sets the status field.
func (b *CommunicationBuilder) WithStatus(v dt.Code) *CommunicationBuilder {
	b.resource.Status = &v
	return b
}

// WithAbout adds an item to the about field.
func (b *CommunicationBuilder) WithAbout(v dt.Reference) *CommunicationBuilder {
	b.resource.About = append(b.resource.About, v)
	return b
}

// WithBasedOn adds an item to the basedOn field.
func (b *CommunicationBuilder) WithBasedOn(v dt.Reference) *CommunicationBuilder {
	b.resource.BasedOn = append(b.resource.BasedOn, v)
	return b
}

// WithCategory adds an item to the category field.
func (b *CommunicationBuilder) WithCategory(v dt.CodeableConcept) *CommunicationBuilder {
	b.resource.Category = append(b.resource.Category, v)
	return b
}

// WithEncounter sets the encounter field.
func (b *CommunicationBuilder) WithEncounter(v dt.Reference) *CommunicationBuilder {
	b.resource.Encounter = &v
	return b
}

// WithInResponseTo adds an item to the inResponseTo field.
func (b *CommunicationBuilder) WithInResponseTo(v dt.Reference) *CommunicationBuilder {
	b.resource.InResponseTo = append(b.resource.InResponseTo, v)
	return b
}

// WithInstantiatesCanonical adds an item to the instantiatesCanonical field.
func (b *CommunicationBuilder) WithInstantiatesCanonical(v dt.Canonical) *CommunicationBuilder {
	b.resource.InstantiatesCanonical = append(b.resource.InstantiatesCanonical, v)
	return b
}

// WithInstantiatesUri adds an item to the instantiatesUri field.
func (b *CommunicationBuilder) WithInstantiatesUri(v dt.URI) *CommunicationBuilder {
	b.resource.InstantiatesUri = append(b.resource.InstantiatesUri, v)
	return b
}

// WithMedium adds an item to the medium field.
func (b *CommunicationBuilder) WithMedium(v dt.CodeableConcept) *CommunicationBuilder {
	b.resource.Medium = append(b.resource.Medium, v)
	return b
}

// WithNote adds an item to the note field.
func (b *CommunicationBuilder) WithNote(v dt.Annotation) *CommunicationBuilder {
	b.resource.Note = append(b.resource.Note, v)
	return b
}

// WithPartOf adds an item to the partOf field.
func (b *CommunicationBuilder) WithPartOf(v dt.Reference) *CommunicationBuilder {
	b.resource.PartOf = append(b.resource.PartOf, v)
	return b
}

// WithPayload adds an item to the payload field.
func (b *CommunicationBuilder) WithPayload(v CommunicationPayload) *CommunicationBuilder {
	b.resource.Payload = append(b.resource.Payload, v)
	return b
}

// WithPriority sets the priority field.
func (b *CommunicationBuilder) WithPriority(v dt.Code) *CommunicationBuilder {
	b.resource.Priority = &v
	return b
}

// WithReasonCode adds an item to the reasonCode field.
func (b *CommunicationBuilder) WithReasonCode(v dt.CodeableConcept) *CommunicationBuilder {
	b.resource.ReasonCode = append(b.resource.ReasonCode, v)
	return b
}

// WithReasonReference adds an item to the reasonReference field.
func (b *CommunicationBuilder) WithReasonReference(v dt.Reference) *CommunicationBuilder {
	b.resource.ReasonReference = append(b.resource.ReasonReference, v)
	return b
}

// WithReceived sets the received field.
func (b *CommunicationBuilder) WithReceived(v dt.DateTime) *CommunicationBuilder {
	b.resource.Received = &v
	return b
}

// WithRecipient adds an item to the recipient field.
func (b *CommunicationBuilder) WithRecipient(v dt.Reference) *CommunicationBuilder {
	b.resource.Recipient = append(b.resource.Recipient, v)
	return b
}

// WithSender sets the sender field.
func (b *CommunicationBuilder) WithSender(v dt.Reference) *CommunicationBuilder {
	b.resource.Sender = &v
	return b
}

// WithSent sets the sent field.
func (b *CommunicationBuilder) WithSent(v dt.DateTime) *CommunicationBuilder {
	b.resource.Sent = &v
	return b
}

// WithStatusReason sets the statusReason field.
func (b *CommunicationBuilder) WithStatusReason(v dt.CodeableConcept) *CommunicationBuilder {
	b.resource.StatusReason = &v
	return b
}

// WithSubject sets the subject field.
func (b *CommunicationBuilder) WithSubject(v dt.Reference) *CommunicationBuilder {
	b.resource.Subject = &v
	return b
}

// WithTopic sets the topic field.
func (b *CommunicationBuilder) WithTopic(v dt.CodeableConcept) *CommunicationBuilder {
	b.resource.Topic = &v
	return b
}

// Build returns the constructed Communication. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *CommunicationBuilder) Build() (*Communication, error) {
	r := b.resource
	return &r, nil
}

// CommunicationPayload An occurrence of information being transmitted; e.g. an alert that was sent to a responsible provider, a public health agency that was notified about a reportable condition.
type CommunicationPayload struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// ContentAttachment A communicated content (or for multi-part communications, one portion of the communication).
	ContentAttachment *dt.Attachment `json:"contentAttachment,omitempty"`
	// ContentReference A communicated content (or for multi-part communications, one portion of the communication).
	ContentReference *dt.Reference `json:"contentReference,omitempty"`
	// ContentString A communicated content (or for multi-part communications, one portion of the communication).
	ContentString *string `json:"contentString,omitempty"`
}
