// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// Contract Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type Contract struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Contract"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Unique identifier for this Contract or a derivative that references a Source Contract.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status The status of the resource instance.
	Status *dt.Code `json:"status,omitempty"`
	// StatusElement contains element extensions for status.
	StatusElement *dt.Element `json:"_status,omitempty"`
	// Alias Alternative representation of the title for this Contract definition, derivative, or instance in any legal state., e.g., a domain specific contract number related to legislation.
	Alias []string `json:"alias,omitempty"`
	// AliasElement contains element extensions for each alias.
	AliasElement []dt.Element `json:"_alias,omitempty"`
	// Applies Relevant time or time-period when this Contract is applicable.
	Applies *dt.Period `json:"applies,omitempty"`
	// Author The individual or organization that authored the Contract definition, derivative, or instance in any legal state.
	Author *dt.Reference `json:"author,omitempty"`
	// Authority A formally or informally recognized grouping of people, principals, organizations, or jurisdictions formed for the purpose of achieving some form of collective action such as the promulgation, admi...
	Authority []dt.Reference `json:"authority,omitempty"`
	// ContentDefinition Precusory content developed with a focus and intent of supporting the formation a Contract instance, which may be associated with and transformable into a Contract.
	ContentDefinition *ContractContentDefinition `json:"contentDefinition,omitempty"`
	// ContentDerivative The minimal content derived from the basal information source at a specific stage in its lifecycle.
	ContentDerivative *dt.CodeableConcept `json:"contentDerivative,omitempty"`
	// Domain Recognized governance framework or system operating with a circumscribed scope in accordance with specified principles, policies, processes or procedures for managing rights, actions, or behaviors ...
	Domain []dt.Reference `json:"domain,omitempty"`
	// ExpirationType Event resulting in discontinuation or termination of this Contract instance by one or more parties to the contract.
	ExpirationType *dt.CodeableConcept `json:"expirationType,omitempty"`
	// Friendly The "patient friendly language" versionof the Contract in whole or in parts. "Patient friendly language" means the representation of the Contract and Contract Provisions in a manner that is readily...
	Friendly []ContractFriendly `json:"friendly,omitempty"`
	// InstantiatesCanonical The URL pointing to a FHIR-defined Contract Definition that is adhered to in whole or part by this Contract.
	InstantiatesCanonical *dt.Reference `json:"instantiatesCanonical,omitempty"`
	// InstantiatesUri The URL pointing to an externally maintained definition that is adhered to in whole or in part by this Contract.
	InstantiatesUri *dt.URI `json:"instantiatesUri,omitempty"`
	// InstantiatesUriElement contains element extensions for instantiatesUri.
	InstantiatesUriElement *dt.Element `json:"_instantiatesUri,omitempty"`
	// Issued When this  Contract was issued.
	Issued *dt.DateTime `json:"issued,omitempty"`
	// IssuedElement contains element extensions for issued.
	IssuedElement *dt.Element `json:"_issued,omitempty"`
	// Legal List of Legal expressions or representations of this Contract.
	Legal []ContractLegal `json:"legal,omitempty"`
	// LegalState Legal states of the formation of a legal instrument, which is a formally executed written document that can be formally attributed to its author, records and formally expresses a legally enforceabl...
	LegalState *dt.CodeableConcept `json:"legalState,omitempty"`
	// LegallyBindingAttachment Legally binding Contract: This is the signed and legally recognized representation of the Contract, which is considered the "source of truth" and which would be the basis for legal action related t...
	LegallyBindingAttachment *dt.Attachment `json:"legallyBindingAttachment,omitempty"`
	// LegallyBindingReference Legally binding Contract: This is the signed and legally recognized representation of the Contract, which is considered the "source of truth" and which would be the basis for legal action related t...
	LegallyBindingReference *dt.Reference `json:"legallyBindingReference,omitempty"`
	// Name A natural language name identifying this Contract definition, derivative, or instance in any legal state. Provides additional information about its content. This name should be usable as an identif...
	Name *string `json:"name,omitempty"`
	// NameElement contains element extensions for name.
	NameElement *dt.Element `json:"_name,omitempty"`
	// RelevantHistory Links to Provenance records for past versions of this Contract definition, derivative, or instance, which identify key state transitions or updates that are likely to be relevant to a user looking ...
	RelevantHistory []dt.Reference `json:"relevantHistory,omitempty"`
	// Rule List of Computable Policy Rule Language Representations of this Contract.
	Rule []ContractRule `json:"rule,omitempty"`
	// Scope A selector of legal concerns for this Contract definition, derivative, or instance in any legal state.
	Scope *dt.CodeableConcept `json:"scope,omitempty"`
	// Signer Parties with legal standing in the Contract, including the principal parties, the grantor(s) and grantee(s), which are any person or organization bound by the contract, and any ancillary parties, w...
	Signer []ContractSigner `json:"signer,omitempty"`
	// Site Sites in which the contract is complied with,  exercised, or in force.
	Site []dt.Reference `json:"site,omitempty"`
	// SubType Sub-category for the Contract that distinguishes the kinds of systems that would be interested in the Contract within the context of the Contract's scope.
	SubType []dt.CodeableConcept `json:"subType,omitempty"`
	// Subject The target entity impacted by or of interest to parties to the agreement.
	Subject []dt.Reference `json:"subject,omitempty"`
	// Subtitle An explanatory or alternate user-friendly title for this Contract definition, derivative, or instance in any legal state.t giving additional information about its content.
	Subtitle *string `json:"subtitle,omitempty"`
	// SubtitleElement contains element extensions for subtitle.
	SubtitleElement *dt.Element `json:"_subtitle,omitempty"`
	// SupportingInfo Information that may be needed by/relevant to the performer in their execution of this term action.
	SupportingInfo []dt.Reference `json:"supportingInfo,omitempty"`
	// Term One or more Contract Provisions, which may be related and conveyed as a group, and may contain nested groups.
	Term []ContractTerm `json:"term,omitempty"`
	// Title A short, descriptive, user-friendly title for this Contract definition, derivative, or instance in any legal state.t giving additional information about its content.
	Title *string `json:"title,omitempty"`
	// TitleElement contains element extensions for title.
	TitleElement *dt.Element `json:"_title,omitempty"`
	// TopicCodeableConcept Narrows the range of legal concerns to focus on the achievement of specific contractual objectives.
	TopicCodeableConcept *dt.CodeableConcept `json:"topicCodeableConcept,omitempty"`
	// TopicReference Narrows the range of legal concerns to focus on the achievement of specific contractual objectives.
	TopicReference *dt.Reference `json:"topicReference,omitempty"`
	// Type A high-level category for the legal instrument, whether constructed as a Contract definition, derivative, or instance in any legal state.  Provides additional information about its content within t...
	Type *dt.CodeableConcept `json:"type,omitempty"`
	// Url Canonical identifier for this contract, represented as a URI (globally unique).
	Url *dt.URI `json:"url,omitempty"`
	// UrlElement contains element extensions for url.
	UrlElement *dt.Element `json:"_url,omitempty"`
	// Version An edition identifier used for business purposes to label business significant variants.
	Version *string `json:"version,omitempty"`
	// VersionElement contains element extensions for version.
	VersionElement *dt.Element `json:"_version,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for Contract.
func (r Contract) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Contract"
	type Alias Contract
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	if len(r.Extra) == 0 {
		return data, nil
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	for k, v := range r.Extra {
		m[k] = v
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for Contract.
func (r *Contract) UnmarshalJSON(data []byte) error {
	type Alias Contract
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Contract(alias)
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_alias", "_applies", "_author", "_authority", "_contained", "_contentDefinition", "_contentDerivative", "_domain", "_expirationType", "_extension", "_friendly", "_id", "_identifier", "_implicitRules", "_instantiatesCanonical", "_instantiatesUri", "_issued", "_language", "_legal", "_legalState", "_legallyBindingAttachment", "_legallyBindingReference", "_meta", "_modifierExtension", "_name", "_relevantHistory", "_rule", "_scope", "_signer", "_site", "_status", "_subType", "_subject", "_subtitle", "_supportingInfo", "_term", "_text", "_title", "_topicCodeableConcept", "_topicReference", "_type", "_url", "_version", "alias", "applies", "author", "authority", "contained", "contentDefinition", "contentDerivative", "domain", "expirationType", "extension", "friendly", "id", "identifier", "implicitRules", "instantiatesCanonical", "instantiatesUri", "issued", "language", "legal", "legalState", "legallyBindingAttachment", "legallyBindingReference", "meta", "modifierExtension", "name", "relevantHistory", "resourceType", "rule", "scope", "signer", "site", "status", "subType", "subject", "subtitle", "supportingInfo", "term", "text", "title", "topicCodeableConcept", "topicReference", "type", "url", "version":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// ContractBuilder provides a fluent API for constructing Contract resources.
type ContractBuilder struct {
	resource  Contract
	fieldsSet map[string]bool
}

// NewContract creates a new ContractBuilder for building a Contract resource.
func NewContract() *ContractBuilder {
	return &ContractBuilder{resource: Contract{ResourceType: "Contract"}, fieldsSet: make(map[string]bool)}
}

// WithId sets the id field.
func (b *ContractBuilder) WithId(v dt.ID) *ContractBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *ContractBuilder) WithMeta(v dt.Meta) *ContractBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *ContractBuilder) WithImplicitRules(v dt.URI) *ContractBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *ContractBuilder) WithLanguage(v dt.Code) *ContractBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *ContractBuilder) WithText(v dt.Narrative) *ContractBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *ContractBuilder) WithContained(v json.RawMessage) *ContractBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *ContractBuilder) WithExtension(v dt.Extension) *ContractBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *ContractBuilder) WithModifierExtension(v dt.Extension) *ContractBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *ContractBuilder) WithIdentifier(v dt.Identifier) *ContractBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	b.fieldsSet["identifier"] = true
	return b
}

// WithStatus sets the status field.
func (b *ContractBuilder) WithStatus(v dt.Code) *ContractBuilder {
	b.resource.Status = &v
	b.fieldsSet["status"] = true
	return b
}

// WithAlias adds an item to the alias field.
func (b *ContractBuilder) WithAlias(v string) *ContractBuilder {
	b.resource.Alias = append(b.resource.Alias, v)
	b.fieldsSet["alias"] = true
	return b
}

// WithApplies sets the applies field.
func (b *ContractBuilder) WithApplies(v dt.Period) *ContractBuilder {
	b.resource.Applies = &v
	b.fieldsSet["applies"] = true
	return b
}

// WithAuthor sets the author field.
func (b *ContractBuilder) WithAuthor(v dt.Reference) *ContractBuilder {
	b.resource.Author = &v
	b.fieldsSet["author"] = true
	return b
}

// WithAuthority adds an item to the authority field.
func (b *ContractBuilder) WithAuthority(v dt.Reference) *ContractBuilder {
	b.resource.Authority = append(b.resource.Authority, v)
	b.fieldsSet["authority"] = true
	return b
}

// WithContentDefinition sets the contentDefinition field.
func (b *ContractBuilder) WithContentDefinition(v ContractContentDefinition) *ContractBuilder {
	b.resource.ContentDefinition = &v
	b.fieldsSet["contentDefinition"] = true
	return b
}

// WithContentDerivative sets the contentDerivative field.
func (b *ContractBuilder) WithContentDerivative(v dt.CodeableConcept) *ContractBuilder {
	b.resource.ContentDerivative = &v
	b.fieldsSet["contentDerivative"] = true
	return b
}

// WithDomain adds an item to the domain field.
func (b *ContractBuilder) WithDomain(v dt.Reference) *ContractBuilder {
	b.resource.Domain = append(b.resource.Domain, v)
	b.fieldsSet["domain"] = true
	return b
}

// WithExpirationType sets the expirationType field.
func (b *ContractBuilder) WithExpirationType(v dt.CodeableConcept) *ContractBuilder {
	b.resource.ExpirationType = &v
	b.fieldsSet["expirationType"] = true
	return b
}

// WithFriendly adds an item to the friendly field.
func (b *ContractBuilder) WithFriendly(v ContractFriendly) *ContractBuilder {
	b.resource.Friendly = append(b.resource.Friendly, v)
	b.fieldsSet["friendly"] = true
	return b
}

// WithInstantiatesCanonical sets the instantiatesCanonical field.
func (b *ContractBuilder) WithInstantiatesCanonical(v dt.Reference) *ContractBuilder {
	b.resource.InstantiatesCanonical = &v
	b.fieldsSet["instantiatesCanonical"] = true
	return b
}

// WithInstantiatesUri sets the instantiatesUri field.
func (b *ContractBuilder) WithInstantiatesUri(v dt.URI) *ContractBuilder {
	b.resource.InstantiatesUri = &v
	b.fieldsSet["instantiatesUri"] = true
	return b
}

// WithIssued sets the issued field.
func (b *ContractBuilder) WithIssued(v dt.DateTime) *ContractBuilder {
	b.resource.Issued = &v
	b.fieldsSet["issued"] = true
	return b
}

// WithLegal adds an item to the legal field.
func (b *ContractBuilder) WithLegal(v ContractLegal) *ContractBuilder {
	b.resource.Legal = append(b.resource.Legal, v)
	b.fieldsSet["legal"] = true
	return b
}

// WithLegalState sets the legalState field.
func (b *ContractBuilder) WithLegalState(v dt.CodeableConcept) *ContractBuilder {
	b.resource.LegalState = &v
	b.fieldsSet["legalState"] = true
	return b
}

// WithLegallyBindingAttachment sets the legallyBindingAttachment field.
func (b *ContractBuilder) WithLegallyBindingAttachment(v dt.Attachment) *ContractBuilder {
	b.resource.LegallyBindingAttachment = &v
	b.fieldsSet["legallyBindingAttachment"] = true
	return b
}

// WithLegallyBindingReference sets the legallyBindingReference field.
func (b *ContractBuilder) WithLegallyBindingReference(v dt.Reference) *ContractBuilder {
	b.resource.LegallyBindingReference = &v
	b.fieldsSet["legallyBindingReference"] = true
	return b
}

// WithName sets the name field.
func (b *ContractBuilder) WithName(v string) *ContractBuilder {
	b.resource.Name = &v
	b.fieldsSet["name"] = true
	return b
}

// WithRelevantHistory adds an item to the relevantHistory field.
func (b *ContractBuilder) WithRelevantHistory(v dt.Reference) *ContractBuilder {
	b.resource.RelevantHistory = append(b.resource.RelevantHistory, v)
	b.fieldsSet["relevantHistory"] = true
	return b
}

// WithRule adds an item to the rule field.
func (b *ContractBuilder) WithRule(v ContractRule) *ContractBuilder {
	b.resource.Rule = append(b.resource.Rule, v)
	b.fieldsSet["rule"] = true
	return b
}

// WithScope sets the scope field.
func (b *ContractBuilder) WithScope(v dt.CodeableConcept) *ContractBuilder {
	b.resource.Scope = &v
	b.fieldsSet["scope"] = true
	return b
}

// WithSigner adds an item to the signer field.
func (b *ContractBuilder) WithSigner(v ContractSigner) *ContractBuilder {
	b.resource.Signer = append(b.resource.Signer, v)
	b.fieldsSet["signer"] = true
	return b
}

// WithSite adds an item to the site field.
func (b *ContractBuilder) WithSite(v dt.Reference) *ContractBuilder {
	b.resource.Site = append(b.resource.Site, v)
	b.fieldsSet["site"] = true
	return b
}

// WithSubType adds an item to the subType field.
func (b *ContractBuilder) WithSubType(v dt.CodeableConcept) *ContractBuilder {
	b.resource.SubType = append(b.resource.SubType, v)
	b.fieldsSet["subType"] = true
	return b
}

// WithSubject adds an item to the subject field.
func (b *ContractBuilder) WithSubject(v dt.Reference) *ContractBuilder {
	b.resource.Subject = append(b.resource.Subject, v)
	b.fieldsSet["subject"] = true
	return b
}

// WithSubtitle sets the subtitle field.
func (b *ContractBuilder) WithSubtitle(v string) *ContractBuilder {
	b.resource.Subtitle = &v
	b.fieldsSet["subtitle"] = true
	return b
}

// WithSupportingInfo adds an item to the supportingInfo field.
func (b *ContractBuilder) WithSupportingInfo(v dt.Reference) *ContractBuilder {
	b.resource.SupportingInfo = append(b.resource.SupportingInfo, v)
	b.fieldsSet["supportingInfo"] = true
	return b
}

// WithTerm adds an item to the term field.
func (b *ContractBuilder) WithTerm(v ContractTerm) *ContractBuilder {
	b.resource.Term = append(b.resource.Term, v)
	b.fieldsSet["term"] = true
	return b
}

// WithTitle sets the title field.
func (b *ContractBuilder) WithTitle(v string) *ContractBuilder {
	b.resource.Title = &v
	b.fieldsSet["title"] = true
	return b
}

// WithTopicCodeableConcept sets the topicCodeableConcept field.
func (b *ContractBuilder) WithTopicCodeableConcept(v dt.CodeableConcept) *ContractBuilder {
	b.resource.TopicCodeableConcept = &v
	b.fieldsSet["topicCodeableConcept"] = true
	return b
}

// WithTopicReference sets the topicReference field.
func (b *ContractBuilder) WithTopicReference(v dt.Reference) *ContractBuilder {
	b.resource.TopicReference = &v
	b.fieldsSet["topicReference"] = true
	return b
}

// WithType sets the type field.
func (b *ContractBuilder) WithType(v dt.CodeableConcept) *ContractBuilder {
	b.resource.Type = &v
	b.fieldsSet["type"] = true
	return b
}

// WithUrl sets the url field.
func (b *ContractBuilder) WithUrl(v dt.URI) *ContractBuilder {
	b.resource.Url = &v
	b.fieldsSet["url"] = true
	return b
}

// WithVersion sets the version field.
func (b *ContractBuilder) WithVersion(v string) *ContractBuilder {
	b.resource.Version = &v
	b.fieldsSet["version"] = true
	return b
}

// Build returns the constructed Contract. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *ContractBuilder) Build() (*Contract, error) {
	r := b.resource
	return &r, nil
}

// ContractAction Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractAction struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Status Current state of the term action.
	Status dt.CodeableConcept `json:"status"`
	// Context Encounter or Episode with primary association to specified term activity.
	Context *dt.Reference `json:"context,omitempty"`
	// ContextLinkId Id [identifier??] of the clause or question text related to the requester of this action in the referenced form or QuestionnaireResponse.
	ContextLinkId []string `json:"contextLinkId,omitempty"`
	// ContextLinkIdElement contains element extensions for each contextLinkId.
	ContextLinkIdElement []dt.Element `json:"_contextLinkId,omitempty"`
	// DoNotPerform True if the term prohibits the  action.
	DoNotPerform *bool `json:"doNotPerform,omitempty"`
	// DoNotPerformElement contains element extensions for doNotPerform.
	DoNotPerformElement *dt.Element `json:"_doNotPerform,omitempty"`
	// Intent Reason or purpose for the action stipulated by this Contract Provision.
	Intent dt.CodeableConcept `json:"intent"`
	// LinkId Id [identifier??] of the clause or question text related to this action in the referenced form or QuestionnaireResponse.
	LinkId []string `json:"linkId,omitempty"`
	// LinkIdElement contains element extensions for each linkId.
	LinkIdElement []dt.Element `json:"_linkId,omitempty"`
	// Note Comments made about the term action made by the requester, performer, subject or other participants.
	Note []dt.Annotation `json:"note,omitempty"`
	// Occurrence When action happens.
	Occurrence *ContractActionOccurrence `json:"-"` // polymorphic
	// Performer Indicates who or what is being asked to perform (or not perform) the ction.
	Performer *dt.Reference `json:"performer,omitempty"`
	// PerformerLinkId Id [identifier??] of the clause or question text related to the reason type or reference of this  action in the referenced form or QuestionnaireResponse.
	PerformerLinkId []string `json:"performerLinkId,omitempty"`
	// PerformerLinkIdElement contains element extensions for each performerLinkId.
	PerformerLinkIdElement []dt.Element `json:"_performerLinkId,omitempty"`
	// PerformerRole The type of role or competency of an individual desired or required to perform or not perform the action.
	PerformerRole *dt.CodeableConcept `json:"performerRole,omitempty"`
	// PerformerType The type of individual that is desired or required to perform or not perform the action.
	PerformerType []dt.CodeableConcept `json:"performerType,omitempty"`
	// Reason Describes why the action is to be performed or not performed in textual form.
	Reason []string `json:"reason,omitempty"`
	// ReasonElement contains element extensions for each reason.
	ReasonElement []dt.Element `json:"_reason,omitempty"`
	// ReasonCode Rationale for the action to be performed or not performed. Describes why the action is permitted or prohibited.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonLinkId Id [identifier??] of the clause or question text related to the reason type or reference of this  action in the referenced form or QuestionnaireResponse.
	ReasonLinkId []string `json:"reasonLinkId,omitempty"`
	// ReasonLinkIdElement contains element extensions for each reasonLinkId.
	ReasonLinkIdElement []dt.Element `json:"_reasonLinkId,omitempty"`
	// ReasonReference Indicates another resource whose existence justifies permitting or not permitting this action.
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// Requester Who or what initiated the action and has responsibility for its activation.
	Requester []dt.Reference `json:"requester,omitempty"`
	// RequesterLinkId Id [identifier??] of the clause or question text related to the requester of this action in the referenced form or QuestionnaireResponse.
	RequesterLinkId []string `json:"requesterLinkId,omitempty"`
	// RequesterLinkIdElement contains element extensions for each requesterLinkId.
	RequesterLinkIdElement []dt.Element `json:"_requesterLinkId,omitempty"`
	// SecurityLabelNumber Security labels that protects the action.
	SecurityLabelNumber []uint32 `json:"securityLabelNumber,omitempty"`
	// SecurityLabelNumberElement contains element extensions for each securityLabelNumber.
	SecurityLabelNumberElement []dt.Element `json:"_securityLabelNumber,omitempty"`
	// Subject Entity of the action.
	Subject []ContractSubject `json:"subject,omitempty"`
	// Type Activity or service obligation to be done or not done, performed or not performed, effectuated or not by this Contract term.
	Type dt.CodeableConcept `json:"type"`
}

// MarshalJSON implements the json.Marshaler interface for ContractAction.
func (r ContractAction) MarshalJSON() ([]byte, error) {
	type Alias ContractAction
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Occurrence != nil {
		vData, err := json.Marshal(r.Occurrence)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractAction.
func (r *ContractAction) UnmarshalJSON(data []byte) error {
	type Alias ContractAction
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = ContractAction(alias)
	var occurrenceVal ContractActionOccurrence
	if err := occurrenceVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if occurrenceVal.DateTime != nil || occurrenceVal.Period != nil || occurrenceVal.Timing != nil {
		r.Occurrence = &occurrenceVal
	}
	return nil
}

// ContractActionOccurrence represents a polymorphic choice type in FHIR.
type ContractActionOccurrence struct {
	DateTime *string    `json:"occurrenceDateTime,omitempty"` // When action happens.
	Period   *dt.Period `json:"occurrencePeriod,omitempty"`   // When action happens.
	Timing   *dt.Timing `json:"occurrenceTiming,omitempty"`   // When action happens.
}

// MarshalJSON implements the json.Marshaler interface for ContractActionOccurrence.
func (v ContractActionOccurrence) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.DateTime != nil {
		m["occurrenceDateTime"] = v.DateTime
	}
	if v.Period != nil {
		m["occurrencePeriod"] = v.Period
	}
	if v.Timing != nil {
		m["occurrenceTiming"] = v.Timing
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractActionOccurrence.
func (v *ContractActionOccurrence) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["occurrenceDateTime"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling occurrenceDateTime: %w", err)
		}
		v.DateTime = &val
	}
	if d, ok := raw["occurrencePeriod"]; ok {
		var val dt.Period
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling occurrencePeriod: %w", err)
		}
		v.Period = &val
	}
	if d, ok := raw["occurrenceTiming"]; ok {
		var val dt.Timing
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling occurrenceTiming: %w", err)
		}
		v.Timing = &val
	}
	return nil
}

// ContractAnswer Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractAnswer struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Value Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Value *ContractAnswerValue `json:"-"` // polymorphic
}

// MarshalJSON implements the json.Marshaler interface for ContractAnswer.
func (r ContractAnswer) MarshalJSON() ([]byte, error) {
	type Alias ContractAnswer
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Value != nil {
		vData, err := json.Marshal(r.Value)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractAnswer.
func (r *ContractAnswer) UnmarshalJSON(data []byte) error {
	type Alias ContractAnswer
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = ContractAnswer(alias)
	var valueVal ContractAnswerValue
	if err := valueVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if valueVal.Attachment != nil || valueVal.Boolean != nil || valueVal.Coding != nil || valueVal.Date != nil || valueVal.DateTime != nil || valueVal.Decimal != nil || valueVal.Integer != nil || valueVal.Quantity != nil || valueVal.Reference != nil || valueVal.String != nil || valueVal.Time != nil || valueVal.Uri != nil {
		r.Value = &valueVal
	}
	return nil
}

// ContractAnswerValue represents a polymorphic choice type in FHIR.
type ContractAnswerValue struct {
	Attachment *dt.Attachment `json:"valueAttachment,omitempty"` // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Boolean    *bool          `json:"valueBoolean,omitempty"`    // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Coding     *dt.Coding     `json:"valueCoding,omitempty"`     // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Date       *string        `json:"valueDate,omitempty"`       // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	DateTime   *string        `json:"valueDateTime,omitempty"`   // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Decimal    *float64       `json:"valueDecimal,omitempty"`    // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Integer    *float64       `json:"valueInteger,omitempty"`    // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Quantity   *dt.Quantity   `json:"valueQuantity,omitempty"`   // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Reference  *dt.Reference  `json:"valueReference,omitempty"`  // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	String     *string        `json:"valueString,omitempty"`     // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Time       *string        `json:"valueTime,omitempty"`       // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
	Uri        *string        `json:"valueUri,omitempty"`        // Response to an offer clause or question text,  which enables selection of values to be agreed to, e.g., the period of participation, the date of occupancy of a rental, warrently duration, or whethe...
}

// MarshalJSON implements the json.Marshaler interface for ContractAnswerValue.
func (v ContractAnswerValue) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.Attachment != nil {
		m["valueAttachment"] = v.Attachment
	}
	if v.Boolean != nil {
		m["valueBoolean"] = v.Boolean
	}
	if v.Coding != nil {
		m["valueCoding"] = v.Coding
	}
	if v.Date != nil {
		m["valueDate"] = v.Date
	}
	if v.DateTime != nil {
		m["valueDateTime"] = v.DateTime
	}
	if v.Decimal != nil {
		m["valueDecimal"] = v.Decimal
	}
	if v.Integer != nil {
		m["valueInteger"] = v.Integer
	}
	if v.Quantity != nil {
		m["valueQuantity"] = v.Quantity
	}
	if v.Reference != nil {
		m["valueReference"] = v.Reference
	}
	if v.String != nil {
		m["valueString"] = v.String
	}
	if v.Time != nil {
		m["valueTime"] = v.Time
	}
	if v.Uri != nil {
		m["valueUri"] = v.Uri
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractAnswerValue.
func (v *ContractAnswerValue) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["valueAttachment"]; ok {
		var val dt.Attachment
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueAttachment: %w", err)
		}
		v.Attachment = &val
	}
	if d, ok := raw["valueBoolean"]; ok {
		var val bool
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueBoolean: %w", err)
		}
		v.Boolean = &val
	}
	if d, ok := raw["valueCoding"]; ok {
		var val dt.Coding
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueCoding: %w", err)
		}
		v.Coding = &val
	}
	if d, ok := raw["valueDate"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueDate: %w", err)
		}
		v.Date = &val
	}
	if d, ok := raw["valueDateTime"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueDateTime: %w", err)
		}
		v.DateTime = &val
	}
	if d, ok := raw["valueDecimal"]; ok {
		var val float64
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueDecimal: %w", err)
		}
		v.Decimal = &val
	}
	if d, ok := raw["valueInteger"]; ok {
		var val float64
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueInteger: %w", err)
		}
		v.Integer = &val
	}
	if d, ok := raw["valueQuantity"]; ok {
		var val dt.Quantity
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueQuantity: %w", err)
		}
		v.Quantity = &val
	}
	if d, ok := raw["valueReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueReference: %w", err)
		}
		v.Reference = &val
	}
	if d, ok := raw["valueString"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueString: %w", err)
		}
		v.String = &val
	}
	if d, ok := raw["valueTime"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueTime: %w", err)
		}
		v.Time = &val
	}
	if d, ok := raw["valueUri"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling valueUri: %w", err)
		}
		v.Uri = &val
	}
	return nil
}

// ContractAsset Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractAsset struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Text Clause or question text (Prose Object) concerning the asset in a linked form, such as a QuestionnaireResponse used in the formation of the contract.
	Text *string `json:"text,omitempty"`
	// TextElement contains element extensions for text.
	TextElement *dt.Element `json:"_text,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Answer Response to assets.
	Answer []ContractAnswer `json:"answer,omitempty"`
	// Condition Description of the quality and completeness of the asset that imay be a factor in its valuation.
	Condition *string `json:"condition,omitempty"`
	// ConditionElement contains element extensions for condition.
	ConditionElement *dt.Element `json:"_condition,omitempty"`
	// Context Circumstance of the asset.
	Context []ContractContext `json:"context,omitempty"`
	// LinkId Id [identifier??] of the clause or question text about the asset in the referenced form or QuestionnaireResponse.
	LinkId []string `json:"linkId,omitempty"`
	// LinkIdElement contains element extensions for each linkId.
	LinkIdElement []dt.Element `json:"_linkId,omitempty"`
	// Period Asset relevant contractual time period.
	Period []dt.Period `json:"period,omitempty"`
	// PeriodType Type of Asset availability for use or ownership.
	PeriodType []dt.CodeableConcept `json:"periodType,omitempty"`
	// Relationship Specifies the applicability of the term to an asset resource instance, and instances it refers to orinstances that refer to it, and/or are owned by the offeree.
	Relationship *dt.Coding `json:"relationship,omitempty"`
	// Scope Differentiates the kind of the asset .
	Scope *dt.CodeableConcept `json:"scope,omitempty"`
	// SecurityLabelNumber Security labels that protects the asset.
	SecurityLabelNumber []uint32 `json:"securityLabelNumber,omitempty"`
	// SecurityLabelNumberElement contains element extensions for each securityLabelNumber.
	SecurityLabelNumberElement []dt.Element `json:"_securityLabelNumber,omitempty"`
	// Subtype May be a subtype or part of an offered asset.
	Subtype []dt.CodeableConcept `json:"subtype,omitempty"`
	// Type Target entity type about which the term may be concerned.
	Type []dt.CodeableConcept `json:"type,omitempty"`
	// TypeReference Associated entities.
	TypeReference []dt.Reference `json:"typeReference,omitempty"`
	// UsePeriod Time period of asset use.
	UsePeriod []dt.Period `json:"usePeriod,omitempty"`
	// ValuedItem Contract Valued Item List.
	ValuedItem []ContractValuedItem `json:"valuedItem,omitempty"`
}

// ContractContentDefinition Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractContentDefinition struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Copyright A copyright statement relating to Contract precursor content. Copyright statements are generally legal restrictions on the use and publishing of the Contract precursor content.
	Copyright *dt.Markdown `json:"copyright,omitempty"`
	// CopyrightElement contains element extensions for copyright.
	CopyrightElement *dt.Element `json:"_copyright,omitempty"`
	// PublicationDate The date (and optionally time) when the contract was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change w...
	PublicationDate *dt.DateTime `json:"publicationDate,omitempty"`
	// PublicationDateElement contains element extensions for publicationDate.
	PublicationDateElement *dt.Element `json:"_publicationDate,omitempty"`
	// PublicationStatus amended | appended | cancelled | disputed | entered-in-error | executable | executed | negotiable | offered | policy | rejected | renewed | revoked | resolved | terminated.
	PublicationStatus *dt.Code `json:"publicationStatus,omitempty"`
	// PublicationStatusElement contains element extensions for publicationStatus.
	PublicationStatusElement *dt.Element `json:"_publicationStatus,omitempty"`
	// Publisher The  individual or organization that published the Contract precursor content.
	Publisher *dt.Reference `json:"publisher,omitempty"`
	// SubType Detailed Precusory content type.
	SubType *dt.CodeableConcept `json:"subType,omitempty"`
	// Type Precusory content structure and use, i.e., a boilerplate, template, application for a contract such as an insurance policy or benefits under a program, e.g., workers compensation.
	Type dt.CodeableConcept `json:"type"`
}

// ContractContext Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractContext struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Text Context description.
	Text *string `json:"text,omitempty"`
	// TextElement contains element extensions for text.
	TextElement *dt.Element `json:"_text,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Code Coded representation of the context generally or of the Referenced entity, such as the asset holder type or location.
	Code []dt.CodeableConcept `json:"code,omitempty"`
	// Reference Asset context reference may include the creator, custodian, or owning Person or Organization (e.g., bank, repository),  location held, e.g., building,  jurisdiction.
	Reference *dt.Reference `json:"reference,omitempty"`
}

// ContractFriendly Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractFriendly struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// ContentAttachment Human readable rendering of this Contract in a format and representation intended to enhance comprehension and ensure understandability.
	ContentAttachment *dt.Attachment `json:"contentAttachment,omitempty"`
	// ContentReference Human readable rendering of this Contract in a format and representation intended to enhance comprehension and ensure understandability.
	ContentReference *dt.Reference `json:"contentReference,omitempty"`
}

// ContractLegal Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractLegal struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// ContentAttachment Contract legal text in human renderable form.
	ContentAttachment *dt.Attachment `json:"contentAttachment,omitempty"`
	// ContentReference Contract legal text in human renderable form.
	ContentReference *dt.Reference `json:"contentReference,omitempty"`
}

// ContractOffer Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractOffer struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Text Human readable form of this Contract Offer.
	Text *string `json:"text,omitempty"`
	// TextElement contains element extensions for text.
	TextElement *dt.Element `json:"_text,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Unique identifier for this particular Contract Provision.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Answer Response to offer text.
	Answer []ContractAnswer `json:"answer,omitempty"`
	// Decision Type of choice made by accepting party with respect to an offer made by an offeror/ grantee.
	Decision *dt.CodeableConcept `json:"decision,omitempty"`
	// DecisionMode How the decision about a Contract was conveyed.
	DecisionMode []dt.CodeableConcept `json:"decisionMode,omitempty"`
	// LinkId The id of the clause or question text of the offer in the referenced questionnaire/response.
	LinkId []string `json:"linkId,omitempty"`
	// LinkIdElement contains element extensions for each linkId.
	LinkIdElement []dt.Element `json:"_linkId,omitempty"`
	// Party Offer Recipient.
	Party []ContractParty `json:"party,omitempty"`
	// SecurityLabelNumber Security labels that protects the offer.
	SecurityLabelNumber []uint32 `json:"securityLabelNumber,omitempty"`
	// SecurityLabelNumberElement contains element extensions for each securityLabelNumber.
	SecurityLabelNumberElement []dt.Element `json:"_securityLabelNumber,omitempty"`
	// Topic The owner of an asset has the residual control rights over the asset: the right to decide all usages of the asset in any way not inconsistent with a prior contract, custom, or law (Hart, 1995, p. 30).
	Topic *dt.Reference `json:"topic,omitempty"`
	// Type Type of Contract Provision such as specific requirements, purposes for actions, obligations, prohibitions, e.g. life time maximum benefit.
	Type *dt.CodeableConcept `json:"type,omitempty"`
}

// ContractParty Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractParty struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Reference Participant in the offer.
	Reference []dt.Reference `json:"reference,omitempty"`
	// Role How the party participates in the offer.
	Role dt.CodeableConcept `json:"role"`
}

// ContractRule Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractRule struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// ContentAttachment Computable Contract conveyed using a policy rule language (e.g. XACML, DKAL, SecPal).
	ContentAttachment *dt.Attachment `json:"contentAttachment,omitempty"`
	// ContentReference Computable Contract conveyed using a policy rule language (e.g. XACML, DKAL, SecPal).
	ContentReference *dt.Reference `json:"contentReference,omitempty"`
}

// ContractSecurityLabel Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractSecurityLabel struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Category Security label privacy tag that species the applicable privacy and security policies governing this term and/or term elements.
	Category []dt.Coding `json:"category,omitempty"`
	// Classification Security label privacy tag that species the level of confidentiality protection required for this term and/or term elements.
	Classification dt.Coding `json:"classification"`
	// Control Security label privacy tag that species the manner in which term and/or term elements are to be protected.
	Control []dt.Coding `json:"control,omitempty"`
	// Number Number used to link this term or term element to the applicable Security Label.
	Number []uint32 `json:"number,omitempty"`
	// NumberElement contains element extensions for each number.
	NumberElement []dt.Element `json:"_number,omitempty"`
}

// ContractSigner Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractSigner struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Party Party which is a signator to this Contract.
	Party dt.Reference `json:"party"`
	// Signature Legally binding Contract DSIG signature contents in Base64.
	Signature []dt.Signature `json:"signature,omitempty"`
	// Type Role of this Contract signer, e.g. notary, grantee.
	Type dt.Coding `json:"type"`
}

// ContractSubject Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractSubject struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Reference The entity the action is performed or not performed on or for.
	Reference []dt.Reference `json:"reference,omitempty"`
	// Role Role type of agent assigned roles in this Contract.
	Role *dt.CodeableConcept `json:"role,omitempty"`
}

// ContractTerm Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractTerm struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Text Statement of a provision in a policy or a contract.
	Text *string `json:"text,omitempty"`
	// TextElement contains element extensions for text.
	TextElement *dt.Element `json:"_text,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Unique identifier for this particular Contract Provision.
	Identifier *dt.Identifier `json:"identifier,omitempty"`
	// Action An actor taking a role in an activity for which it can be assigned some degree of responsibility for the activity taking place.
	Action []ContractAction `json:"action,omitempty"`
	// Applies Relevant time or time-period when this Contract Provision is applicable.
	Applies *dt.Period `json:"applies,omitempty"`
	// Asset Contract Term Asset List.
	Asset []ContractAsset `json:"asset,omitempty"`
	// Group Nested group of Contract Provisions.
	Group []ContractTerm `json:"group,omitempty"`
	// Issued When this Contract Provision was issued.
	Issued *dt.DateTime `json:"issued,omitempty"`
	// IssuedElement contains element extensions for issued.
	IssuedElement *dt.Element `json:"_issued,omitempty"`
	// Offer The matter of concern in the context of this provision of the agrement.
	Offer ContractOffer `json:"offer"`
	// SecurityLabel Security labels that protect the handling of information about the term and its elements, which may be specifically identified..
	SecurityLabel []ContractSecurityLabel `json:"securityLabel,omitempty"`
	// SubType A specialized legal clause or condition based on overarching contract type.
	SubType *dt.CodeableConcept `json:"subType,omitempty"`
	// TopicCodeableConcept The entity that the term applies to.
	TopicCodeableConcept *dt.CodeableConcept `json:"topicCodeableConcept,omitempty"`
	// TopicReference The entity that the term applies to.
	TopicReference *dt.Reference `json:"topicReference,omitempty"`
	// Type A legal clause or condition contained within a contract that requires one or both parties to perform a particular requirement by some specified time or prevents one or both parties from performing ...
	Type *dt.CodeableConcept `json:"type,omitempty"`
}

// ContractValuedItem Legally enforceable, formally recorded unilateral or bilateral directive i.e., a policy or agreement.
type ContractValuedItem struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Identifies a Contract Valued Item instance.
	Identifier *dt.Identifier `json:"identifier,omitempty"`
	// EffectiveTime Indicates the time during which this Contract ValuedItem information is effective.
	EffectiveTime *dt.DateTime `json:"effectiveTime,omitempty"`
	// EffectiveTimeElement contains element extensions for effectiveTime.
	EffectiveTimeElement *dt.Element `json:"_effectiveTime,omitempty"`
	// Entity Specific type of Contract Valued Item that may be priced.
	Entity *ContractValuedItemEntity `json:"-"` // polymorphic
	// Factor A real number that represents a multiplier used in determining the overall value of the Contract Valued Item delivered. The concept of a Factor allows for a discount or surcharge multiplier to be a...
	Factor *float64 `json:"factor,omitempty"`
	// FactorElement contains element extensions for factor.
	FactorElement *dt.Element `json:"_factor,omitempty"`
	// LinkId Id  of the clause or question text related to the context of this valuedItem in the referenced form or QuestionnaireResponse.
	LinkId []string `json:"linkId,omitempty"`
	// LinkIdElement contains element extensions for each linkId.
	LinkIdElement []dt.Element `json:"_linkId,omitempty"`
	// Net Expresses the product of the Contract Valued Item unitQuantity and the unitPriceAmt. For example, the formula: unit Quantity * unit Price (Cost per Point) * factor Number  * points = net Amount. Qu...
	Net *dt.Money `json:"net,omitempty"`
	// Payment Terms of valuation.
	Payment *string `json:"payment,omitempty"`
	// PaymentElement contains element extensions for payment.
	PaymentElement *dt.Element `json:"_payment,omitempty"`
	// PaymentDate When payment is due.
	PaymentDate *dt.DateTime `json:"paymentDate,omitempty"`
	// PaymentDateElement contains element extensions for paymentDate.
	PaymentDateElement *dt.Element `json:"_paymentDate,omitempty"`
	// Points An amount that expresses the weighting (based on difficulty, cost and/or resource intensiveness) associated with the Contract Valued Item delivered. The concept of Points allows for assignment of p...
	Points *float64 `json:"points,omitempty"`
	// PointsElement contains element extensions for points.
	PointsElement *dt.Element `json:"_points,omitempty"`
	// Quantity Specifies the units by which the Contract Valued Item is measured or counted, and quantifies the countable or measurable Contract Valued Item instances.
	Quantity *dt.Quantity `json:"quantity,omitempty"`
	// Recipient Who will receive payment.
	Recipient *dt.Reference `json:"recipient,omitempty"`
	// Responsible Who will make payment.
	Responsible *dt.Reference `json:"responsible,omitempty"`
	// SecurityLabelNumber A set of security labels that define which terms are controlled by this condition.
	SecurityLabelNumber []uint32 `json:"securityLabelNumber,omitempty"`
	// SecurityLabelNumberElement contains element extensions for each securityLabelNumber.
	SecurityLabelNumberElement []dt.Element `json:"_securityLabelNumber,omitempty"`
	// UnitPrice A Contract Valued Item unit valuation measure.
	UnitPrice *dt.Money `json:"unitPrice,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for ContractValuedItem.
func (r ContractValuedItem) MarshalJSON() ([]byte, error) {
	type Alias ContractValuedItem
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Entity != nil {
		vData, err := json.Marshal(r.Entity)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractValuedItem.
func (r *ContractValuedItem) UnmarshalJSON(data []byte) error {
	type Alias ContractValuedItem
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = ContractValuedItem(alias)
	var entityVal ContractValuedItemEntity
	if err := entityVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if entityVal.CodeableConcept != nil || entityVal.Reference != nil {
		r.Entity = &entityVal
	}
	return nil
}

// ContractValuedItemEntity represents a polymorphic choice type in FHIR.
type ContractValuedItemEntity struct {
	CodeableConcept *dt.CodeableConcept `json:"entityCodeableConcept,omitempty"` // Specific type of Contract Valued Item that may be priced.
	Reference       *dt.Reference       `json:"entityReference,omitempty"`       // Specific type of Contract Valued Item that may be priced.
}

// MarshalJSON implements the json.Marshaler interface for ContractValuedItemEntity.
func (v ContractValuedItemEntity) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.CodeableConcept != nil {
		m["entityCodeableConcept"] = v.CodeableConcept
	}
	if v.Reference != nil {
		m["entityReference"] = v.Reference
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContractValuedItemEntity.
func (v *ContractValuedItemEntity) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["entityCodeableConcept"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling entityCodeableConcept: %w", err)
		}
		v.CodeableConcept = &val
	}
	if d, ok := raw["entityReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling entityReference: %w", err)
		}
		v.Reference = &val
	}
	return nil
}
