// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// Goal Describes the intended objective(s) for a patient, group or organization care, for example, weight loss, restoring an activity of daily living, obtaining herd immunity via immunization, meeting a p...
type Goal struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "Goal"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Business identifiers assigned to this goal by the performer or other systems which remain constant as the resource is updated and propagates from server to server.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// AchievementStatus Describes the progression, or lack thereof, towards the goal against the target.
	AchievementStatus *dt.CodeableConcept `json:"achievementStatus,omitempty"`
	// Addresses The identified conditions and other health record elements that are intended to be addressed by the goal.
	Addresses []dt.Reference `json:"addresses,omitempty"`
	// Category Indicates a category the goal falls within.
	Category []dt.CodeableConcept `json:"category,omitempty"`
	// Description Human-readable and/or coded description of a specific desired objective of care, such as "control blood pressure" or "negotiate an obstacle course" or "dance with child at wedding".
	Description dt.CodeableConcept `json:"description"`
	// ExpressedBy Indicates whose goal this is - patient goal, practitioner goal, etc.
	ExpressedBy *dt.Reference `json:"expressedBy,omitempty"`
	// LifecycleStatus The state of the goal throughout its lifecycle.
	LifecycleStatus *GoalLifecycleStatus `json:"lifecycleStatus,omitempty"`
	// Note Any comments related to the goal.
	Note []dt.Annotation `json:"note,omitempty"`
	// OutcomeCode Identifies the change (or lack of change) at the point when the status of the goal is assessed.
	OutcomeCode []dt.CodeableConcept `json:"outcomeCode,omitempty"`
	// OutcomeReference Details of what's changed (or not changed).
	OutcomeReference []dt.Reference `json:"outcomeReference,omitempty"`
	// Priority Identifies the mutually agreed level of importance associated with reaching/sustaining the goal.
	Priority *dt.CodeableConcept `json:"priority,omitempty"`
	// StartCodeableConcept The date or event after which the goal should begin being pursued.
	StartCodeableConcept *dt.CodeableConcept `json:"startCodeableConcept,omitempty"`
	// StartDate The date or event after which the goal should begin being pursued.
	StartDate *string `json:"startDate,omitempty"`
	// StatusDate Identifies when the current status.  I.e. When initially created, when achieved, when cancelled, etc.
	StatusDate *dt.Date `json:"statusDate,omitempty"`
	// StatusReason Captures the reason for the current status.
	StatusReason *string `json:"statusReason,omitempty"`
	// Subject Identifies the patient, group or organization for whom the goal is being established.
	Subject dt.Reference `json:"subject"`
	// Target Indicates what should be done by when.
	Target []GoalTarget `json:"target,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for Goal.
func (r Goal) MarshalJSON() ([]byte, error) {
	r.ResourceType = "Goal"
	type Alias Goal
	return json.Marshal((Alias)(r))
}

// UnmarshalJSON implements the json.Unmarshaler interface for Goal.
func (r *Goal) UnmarshalJSON(data []byte) error {
	type Alias Goal
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = Goal(alias)
	return nil
}

// GoalBuilder provides a fluent API for constructing Goal resources.
type GoalBuilder struct {
	resource Goal
}

// NewGoal creates a new GoalBuilder for building a Goal resource.
func NewGoal() *GoalBuilder {
	return &GoalBuilder{resource: Goal{ResourceType: "Goal"}}
}

// WithId sets the id field.
func (b *GoalBuilder) WithId(v dt.ID) *GoalBuilder {
	b.resource.Id = &v
	return b
}

// WithMeta sets the meta field.
func (b *GoalBuilder) WithMeta(v dt.Meta) *GoalBuilder {
	b.resource.Meta = &v
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *GoalBuilder) WithImplicitRules(v dt.URI) *GoalBuilder {
	b.resource.ImplicitRules = &v
	return b
}

// WithLanguage sets the language field.
func (b *GoalBuilder) WithLanguage(v dt.Code) *GoalBuilder {
	b.resource.Language = &v
	return b
}

// WithText sets the text field.
func (b *GoalBuilder) WithText(v dt.Narrative) *GoalBuilder {
	b.resource.Text = &v
	return b
}

// WithContained adds an item to the contained field.
func (b *GoalBuilder) WithContained(v json.RawMessage) *GoalBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	return b
}

// WithExtension adds an item to the extension field.
func (b *GoalBuilder) WithExtension(v dt.Extension) *GoalBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *GoalBuilder) WithModifierExtension(v dt.Extension) *GoalBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *GoalBuilder) WithIdentifier(v dt.Identifier) *GoalBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	return b
}

// WithAchievementStatus sets the achievementStatus field.
func (b *GoalBuilder) WithAchievementStatus(v dt.CodeableConcept) *GoalBuilder {
	b.resource.AchievementStatus = &v
	return b
}

// WithAddresses adds an item to the addresses field.
func (b *GoalBuilder) WithAddresses(v dt.Reference) *GoalBuilder {
	b.resource.Addresses = append(b.resource.Addresses, v)
	return b
}

// WithCategory adds an item to the category field.
func (b *GoalBuilder) WithCategory(v dt.CodeableConcept) *GoalBuilder {
	b.resource.Category = append(b.resource.Category, v)
	return b
}

// WithDescription sets the description field.
func (b *GoalBuilder) WithDescription(v dt.CodeableConcept) *GoalBuilder {
	b.resource.Description = v
	return b
}

// WithExpressedBy sets the expressedBy field.
func (b *GoalBuilder) WithExpressedBy(v dt.Reference) *GoalBuilder {
	b.resource.ExpressedBy = &v
	return b
}

// WithLifecycleStatus sets the lifecycleStatus field.
func (b *GoalBuilder) WithLifecycleStatus(v GoalLifecycleStatus) *GoalBuilder {
	b.resource.LifecycleStatus = &v
	return b
}

// WithNote adds an item to the note field.
func (b *GoalBuilder) WithNote(v dt.Annotation) *GoalBuilder {
	b.resource.Note = append(b.resource.Note, v)
	return b
}

// WithOutcomeCode adds an item to the outcomeCode field.
func (b *GoalBuilder) WithOutcomeCode(v dt.CodeableConcept) *GoalBuilder {
	b.resource.OutcomeCode = append(b.resource.OutcomeCode, v)
	return b
}

// WithOutcomeReference adds an item to the outcomeReference field.
func (b *GoalBuilder) WithOutcomeReference(v dt.Reference) *GoalBuilder {
	b.resource.OutcomeReference = append(b.resource.OutcomeReference, v)
	return b
}

// WithPriority sets the priority field.
func (b *GoalBuilder) WithPriority(v dt.CodeableConcept) *GoalBuilder {
	b.resource.Priority = &v
	return b
}

// WithStartCodeableConcept sets the startCodeableConcept field.
func (b *GoalBuilder) WithStartCodeableConcept(v dt.CodeableConcept) *GoalBuilder {
	b.resource.StartCodeableConcept = &v
	return b
}

// WithStartDate sets the startDate field.
func (b *GoalBuilder) WithStartDate(v string) *GoalBuilder {
	b.resource.StartDate = &v
	return b
}

// WithStatusDate sets the statusDate field.
func (b *GoalBuilder) WithStatusDate(v dt.Date) *GoalBuilder {
	b.resource.StatusDate = &v
	return b
}

// WithStatusReason sets the statusReason field.
func (b *GoalBuilder) WithStatusReason(v string) *GoalBuilder {
	b.resource.StatusReason = &v
	return b
}

// WithSubject sets the subject field.
func (b *GoalBuilder) WithSubject(v dt.Reference) *GoalBuilder {
	b.resource.Subject = v
	return b
}

// WithTarget adds an item to the target field.
func (b *GoalBuilder) WithTarget(v GoalTarget) *GoalBuilder {
	b.resource.Target = append(b.resource.Target, v)
	return b
}

// Build returns the constructed Goal. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *GoalBuilder) Build() (*Goal, error) {
	r := b.resource
	return &r, nil
}

// GoalTarget Describes the intended objective(s) for a patient, group or organization care, for example, weight loss, restoring an activity of daily living, obtaining herd immunity via immunization, meeting a p...
type GoalTarget struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// DetailBoolean The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailBoolean *bool `json:"detailBoolean,omitempty"`
	// DetailCodeableConcept The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailCodeableConcept *dt.CodeableConcept `json:"detailCodeableConcept,omitempty"`
	// DetailInteger The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailInteger *float64 `json:"detailInteger,omitempty"`
	// DetailQuantity The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailQuantity *dt.Quantity `json:"detailQuantity,omitempty"`
	// DetailRange The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailRange *dt.Range `json:"detailRange,omitempty"`
	// DetailRatio The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailRatio *dt.Ratio `json:"detailRatio,omitempty"`
	// DetailString The target value of the focus to be achieved to signify the fulfillment of the goal, e.g. 150 pounds, 7.0%. Either the high or low or both values of the range can be specified. When a low value is ...
	DetailString *string `json:"detailString,omitempty"`
	// DueDate Indicates either the date or the duration after start by which the goal should be met.
	DueDate *string `json:"dueDate,omitempty"`
	// DueDuration Indicates either the date or the duration after start by which the goal should be met.
	DueDuration *dt.Duration `json:"dueDuration,omitempty"`
	// Measure The parameter whose value is being tracked, e.g. body weight, blood pressure, or hemoglobin A1c level.
	Measure *dt.CodeableConcept `json:"measure,omitempty"`
}
