// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// MedicationRequest An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPresc...
type MedicationRequest struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "MedicationRequest"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Identifiers associated with this medication request that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are...
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status A code specifying the current state of the order.  Generally, this will be active or completed state.
	Status *dt.Code `json:"status,omitempty"`
	// StatusElement contains element extensions for status.
	StatusElement *dt.Element `json:"_status,omitempty"`
	// AuthoredOn The date (and perhaps time) when the prescription was initially written or authored on.
	AuthoredOn *dt.DateTime `json:"authoredOn,omitempty"`
	// AuthoredOnElement contains element extensions for authoredOn.
	AuthoredOnElement *dt.Element `json:"_authoredOn,omitempty"`
	// BasedOn A plan or request that is fulfilled in whole or in part by this medication request.
	BasedOn []dt.Reference `json:"basedOn,omitempty"`
	// Category Indicates the type of medication request (for example, where the medication is expected to be consumed or administered (i.e. inpatient or outpatient)).
	Category []dt.CodeableConcept `json:"category,omitempty"`
	// CourseOfTherapyType The description of the overall patte3rn of the administration of the medication to the patient.
	CourseOfTherapyType *dt.CodeableConcept `json:"courseOfTherapyType,omitempty"`
	// DetectedIssue Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. Drug-drug interaction, duplicate therapy, dosage alert etc.
	DetectedIssue []dt.Reference `json:"detectedIssue,omitempty"`
	// DispenseRequest Indicates the specific details for the dispense or medication supply part of a medication request (also known as a Medication Prescription or Medication Order).  Note that this information is not a...
	DispenseRequest *MedicationRequestDispenseRequest `json:"dispenseRequest,omitempty"`
	// DoNotPerform If true indicates that the provider is asking for the medication request not to occur.
	DoNotPerform *bool `json:"doNotPerform,omitempty"`
	// DoNotPerformElement contains element extensions for doNotPerform.
	DoNotPerformElement *dt.Element `json:"_doNotPerform,omitempty"`
	// DosageInstruction Indicates how the medication is to be used by the patient.
	DosageInstruction []dt.Dosage `json:"dosageInstruction,omitempty"`
	// Encounter The Encounter during which this [x] was created or to which the creation of this record is tightly associated.
	Encounter *dt.Reference `json:"encounter,omitempty"`
	// EventHistory Links to Provenance records for past versions of this resource or fulfilling request or event resources that identify key state transitions or updates that are likely to be relevant to a user looki...
	EventHistory []dt.Reference `json:"eventHistory,omitempty"`
	// GroupIdentifier A shared identifier common to all requests that were authorized more or less simultaneously by a single author, representing the identifier of the requisition or prescription.
	GroupIdentifier *dt.Identifier `json:"groupIdentifier,omitempty"`
	// InstantiatesCanonical The URL pointing to a protocol, guideline, orderset, or other definition that is adhered to in whole or in part by this MedicationRequest.
	InstantiatesCanonical []dt.Canonical `json:"instantiatesCanonical,omitempty"`
	// InstantiatesCanonicalElement contains element extensions for each instantiatesCanonical.
	InstantiatesCanonicalElement []dt.Element `json:"_instantiatesCanonical,omitempty"`
	// InstantiatesUri The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this MedicationRequest.
	InstantiatesUri []dt.URI `json:"instantiatesUri,omitempty"`
	// InstantiatesUriElement contains element extensions for each instantiatesUri.
	InstantiatesUriElement []dt.Element `json:"_instantiatesUri,omitempty"`
	// Insurance Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be required for delivering the requested service.
	Insurance []dt.Reference `json:"insurance,omitempty"`
	// Intent Whether the request is a proposal, plan, or an original order.
	Intent *dt.Code `json:"intent,omitempty"`
	// IntentElement contains element extensions for intent.
	IntentElement *dt.Element `json:"_intent,omitempty"`
	// Medication Identifies the medication being requested. This is a link to a resource that represents the medication which may be the details of the medication or simply an attribute carrying a code that identif...
	Medication *MedicationRequestMedication `json:"-"` // polymorphic
	// Note Extra information about the prescription that could not be conveyed by the other attributes.
	Note []dt.Annotation `json:"note,omitempty"`
	// Performer The specified desired performer of the medication treatment (e.g. the performer of the medication administration).
	Performer *dt.Reference `json:"performer,omitempty"`
	// PerformerType Indicates the type of performer of the administration of the medication.
	PerformerType *dt.CodeableConcept `json:"performerType,omitempty"`
	// PriorPrescription A link to a resource representing an earlier order related order or prescription.
	PriorPrescription *dt.Reference `json:"priorPrescription,omitempty"`
	// Priority Indicates how quickly the Medication Request should be addressed with respect to other requests.
	Priority *dt.Code `json:"priority,omitempty"`
	// PriorityElement contains element extensions for priority.
	PriorityElement *dt.Element `json:"_priority,omitempty"`
	// ReasonCode The reason or the indication for ordering or not ordering the medication.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonReference Condition or observation that supports why the medication was ordered.
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// Recorder The person who entered the order on behalf of another individual for example in the case of a verbal or a telephone order.
	Recorder *dt.Reference `json:"recorder,omitempty"`
	// Reported Indicates if this record was captured as a secondary 'reported' record rather than as an original primary source-of-truth record.  It may also indicate the source of the report.
	Reported *MedicationRequestReported `json:"-"` // polymorphic
	// Requester The individual, organization, or device that initiated the request and has responsibility for its activation.
	Requester *dt.Reference `json:"requester,omitempty"`
	// StatusReason Captures the reason for the current state of the MedicationRequest.
	StatusReason *dt.CodeableConcept `json:"statusReason,omitempty"`
	// Subject A link to a resource representing the person or set of individuals to whom the medication will be given.
	Subject dt.Reference `json:"subject"`
	// Substitution Indicates whether or not substitution can or should be part of the dispense. In some cases, substitution must happen, in other cases substitution must not happen. This block explains the prescriber...
	Substitution *MedicationRequestSubstitution `json:"substitution,omitempty"`
	// SupportingInformation Include additional information (for example, patient height and weight) that supports the ordering of the medication.
	SupportingInformation []dt.Reference `json:"supportingInformation,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for MedicationRequest.
func (r MedicationRequest) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicationRequest"
	type Alias MedicationRequest
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Medication != nil {
		vData, err := json.Marshal(r.Medication)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	if r.Reported != nil {
		vData, err := json.Marshal(r.Reported)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	for k, v := range r.Extra {
		m[k] = v
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationRequest.
func (r *MedicationRequest) UnmarshalJSON(data []byte) error {
	type Alias MedicationRequest
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicationRequest(alias)
	// Unmarshal polymorphic fields
	var medicationVal MedicationRequestMedication
	if err := medicationVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if medicationVal.CodeableConcept != nil || medicationVal.Reference != nil {
		r.Medication = &medicationVal
	}
	var reportedVal MedicationRequestReported
	if err := reportedVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if reportedVal.Boolean != nil || reportedVal.Reference != nil {
		r.Reported = &reportedVal
	}
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_authoredOn", "_basedOn", "_category", "_contained", "_courseOfTherapyType", "_detectedIssue", "_dispenseRequest", "_doNotPerform", "_dosageInstruction", "_encounter", "_eventHistory", "_extension", "_groupIdentifier", "_id", "_identifier", "_implicitRules", "_instantiatesCanonical", "_instantiatesUri", "_insurance", "_intent", "_language", "_medicationCodeableConcept", "_medicationReference", "_meta", "_modifierExtension", "_note", "_performer", "_performerType", "_priorPrescription", "_priority", "_reasonCode", "_reasonReference", "_recorder", "_reportedBoolean", "_reportedReference", "_requester", "_status", "_statusReason", "_subject", "_substitution", "_supportingInformation", "_text", "authoredOn", "basedOn", "category", "contained", "courseOfTherapyType", "detectedIssue", "dispenseRequest", "doNotPerform", "dosageInstruction", "encounter", "eventHistory", "extension", "groupIdentifier", "id", "identifier", "implicitRules", "instantiatesCanonical", "instantiatesUri", "insurance", "intent", "language", "medicationCodeableConcept", "medicationReference", "meta", "modifierExtension", "note", "performer", "performerType", "priorPrescription", "priority", "reasonCode", "reasonReference", "recorder", "reportedBoolean", "reportedReference", "requester", "resourceType", "status", "statusReason", "subject", "substitution", "supportingInformation", "text":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// MedicationRequestBuilder provides a fluent API for constructing MedicationRequest resources.
type MedicationRequestBuilder struct {
	resource  MedicationRequest
	fieldsSet map[string]bool
}

// NewMedicationRequest creates a new MedicationRequestBuilder for building a MedicationRequest resource.
func NewMedicationRequest() *MedicationRequestBuilder {
	return &MedicationRequestBuilder{resource: MedicationRequest{ResourceType: "MedicationRequest"}, fieldsSet: make(map[string]bool)}
}

// WithStatus sets the medication request status.
func (b *MedicationRequestBuilder) WithStatus(status dt.Code) *MedicationRequestBuilder {
	b.resource.Status = &status
	b.fieldsSet["status"] = true
	return b
}

// WithIntent sets the medication request intent.
func (b *MedicationRequestBuilder) WithIntent(intent dt.Code) *MedicationRequestBuilder {
	b.resource.Intent = &intent
	b.fieldsSet["intent"] = true
	return b
}

// WithSubject sets the medication request subject reference.
func (b *MedicationRequestBuilder) WithSubject(reference string) *MedicationRequestBuilder {
	b.resource.Subject = dt.Reference{Reference: &reference}
	b.fieldsSet["subject"] = true
	return b
}

// WithMedicationCodeableConcept sets the medication as a CodeableConcept.
func (b *MedicationRequestBuilder) WithMedicationCodeableConcept(system, code, display string) *MedicationRequestBuilder {
	s := dt.URI(system)
	c := dt.Code(code)
	cc := dt.CodeableConcept{
		Coding: []dt.Coding{{
			System:  &s,
			Code:    &c,
			Display: &display,
		}},
	}
	if b.resource.Medication == nil {
		b.resource.Medication = &MedicationRequestMedication{}
	}
	b.resource.Medication.CodeableConcept = &cc
	b.fieldsSet["medication"] = true
	return b
}

// WithId sets the id field.
func (b *MedicationRequestBuilder) WithId(v dt.ID) *MedicationRequestBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *MedicationRequestBuilder) WithMeta(v dt.Meta) *MedicationRequestBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *MedicationRequestBuilder) WithImplicitRules(v dt.URI) *MedicationRequestBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *MedicationRequestBuilder) WithLanguage(v dt.Code) *MedicationRequestBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *MedicationRequestBuilder) WithText(v dt.Narrative) *MedicationRequestBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *MedicationRequestBuilder) WithContained(v json.RawMessage) *MedicationRequestBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *MedicationRequestBuilder) WithExtension(v dt.Extension) *MedicationRequestBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *MedicationRequestBuilder) WithModifierExtension(v dt.Extension) *MedicationRequestBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *MedicationRequestBuilder) WithIdentifier(v dt.Identifier) *MedicationRequestBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	b.fieldsSet["identifier"] = true
	return b
}

// WithAuthoredOn sets the authoredOn field.
func (b *MedicationRequestBuilder) WithAuthoredOn(v dt.DateTime) *MedicationRequestBuilder {
	b.resource.AuthoredOn = &v
	b.fieldsSet["authoredOn"] = true
	return b
}

// WithBasedOn adds an item to the basedOn field.
func (b *MedicationRequestBuilder) WithBasedOn(v dt.Reference) *MedicationRequestBuilder {
	b.resource.BasedOn = append(b.resource.BasedOn, v)
	b.fieldsSet["basedOn"] = true
	return b
}

// WithCategory adds an item to the category field.
func (b *MedicationRequestBuilder) WithCategory(v dt.CodeableConcept) *MedicationRequestBuilder {
	b.resource.Category = append(b.resource.Category, v)
	b.fieldsSet["category"] = true
	return b
}

// WithCourseOfTherapyType sets the courseOfTherapyType field.
func (b *MedicationRequestBuilder) WithCourseOfTherapyType(v dt.CodeableConcept) *MedicationRequestBuilder {
	b.resource.CourseOfTherapyType = &v
	b.fieldsSet["courseOfTherapyType"] = true
	return b
}

// WithDetectedIssue adds an item to the detectedIssue field.
func (b *MedicationRequestBuilder) WithDetectedIssue(v dt.Reference) *MedicationRequestBuilder {
	b.resource.DetectedIssue = append(b.resource.DetectedIssue, v)
	b.fieldsSet["detectedIssue"] = true
	return b
}

// WithDispenseRequest sets the dispenseRequest field.
func (b *MedicationRequestBuilder) WithDispenseRequest(v MedicationRequestDispenseRequest) *MedicationRequestBuilder {
	b.resource.DispenseRequest = &v
	b.fieldsSet["dispenseRequest"] = true
	return b
}

// WithDoNotPerform sets the doNotPerform field.
func (b *MedicationRequestBuilder) WithDoNotPerform(v bool) *MedicationRequestBuilder {
	b.resource.DoNotPerform = &v
	b.fieldsSet["doNotPerform"] = true
	return b
}

// WithDosageInstruction adds an item to the dosageInstruction field.
func (b *MedicationRequestBuilder) WithDosageInstruction(v dt.Dosage) *MedicationRequestBuilder {
	b.resource.DosageInstruction = append(b.resource.DosageInstruction, v)
	b.fieldsSet["dosageInstruction"] = true
	return b
}

// WithEncounter sets the encounter field.
func (b *MedicationRequestBuilder) WithEncounter(v dt.Reference) *MedicationRequestBuilder {
	b.resource.Encounter = &v
	b.fieldsSet["encounter"] = true
	return b
}

// WithEventHistory adds an item to the eventHistory field.
func (b *MedicationRequestBuilder) WithEventHistory(v dt.Reference) *MedicationRequestBuilder {
	b.resource.EventHistory = append(b.resource.EventHistory, v)
	b.fieldsSet["eventHistory"] = true
	return b
}

// WithGroupIdentifier sets the groupIdentifier field.
func (b *MedicationRequestBuilder) WithGroupIdentifier(v dt.Identifier) *MedicationRequestBuilder {
	b.resource.GroupIdentifier = &v
	b.fieldsSet["groupIdentifier"] = true
	return b
}

// WithInstantiatesCanonical adds an item to the instantiatesCanonical field.
func (b *MedicationRequestBuilder) WithInstantiatesCanonical(v dt.Canonical) *MedicationRequestBuilder {
	b.resource.InstantiatesCanonical = append(b.resource.InstantiatesCanonical, v)
	b.fieldsSet["instantiatesCanonical"] = true
	return b
}

// WithInstantiatesUri adds an item to the instantiatesUri field.
func (b *MedicationRequestBuilder) WithInstantiatesUri(v dt.URI) *MedicationRequestBuilder {
	b.resource.InstantiatesUri = append(b.resource.InstantiatesUri, v)
	b.fieldsSet["instantiatesUri"] = true
	return b
}

// WithInsurance adds an item to the insurance field.
func (b *MedicationRequestBuilder) WithInsurance(v dt.Reference) *MedicationRequestBuilder {
	b.resource.Insurance = append(b.resource.Insurance, v)
	b.fieldsSet["insurance"] = true
	return b
}

// WithMedicationReference sets the medicationReference polymorphic field.
func (b *MedicationRequestBuilder) WithMedicationReference(v dt.Reference) *MedicationRequestBuilder {
	if b.resource.Medication == nil {
		b.resource.Medication = &MedicationRequestMedication{}
	}
	b.resource.Medication.Reference = &v
	b.fieldsSet["medication"] = true
	return b
}

// WithNote adds an item to the note field.
func (b *MedicationRequestBuilder) WithNote(v dt.Annotation) *MedicationRequestBuilder {
	b.resource.Note = append(b.resource.Note, v)
	b.fieldsSet["note"] = true
	return b
}

// WithPerformer sets the performer field.
func (b *MedicationRequestBuilder) WithPerformer(v dt.Reference) *MedicationRequestBuilder {
	b.resource.Performer = &v
	b.fieldsSet["performer"] = true
	return b
}

// WithPerformerType sets the performerType field.
func (b *MedicationRequestBuilder) WithPerformerType(v dt.CodeableConcept) *MedicationRequestBuilder {
	b.resource.PerformerType = &v
	b.fieldsSet["performerType"] = true
	return b
}

// WithPriorPrescription sets the priorPrescription field.
func (b *MedicationRequestBuilder) WithPriorPrescription(v dt.Reference) *MedicationRequestBuilder {
	b.resource.PriorPrescription = &v
	b.fieldsSet["priorPrescription"] = true
	return b
}

// WithPriority sets the priority field.
func (b *MedicationRequestBuilder) WithPriority(v dt.Code) *MedicationRequestBuilder {
	b.resource.Priority = &v
	b.fieldsSet["priority"] = true
	return b
}

// WithReasonCode adds an item to the reasonCode field.
func (b *MedicationRequestBuilder) WithReasonCode(v dt.CodeableConcept) *MedicationRequestBuilder {
	b.resource.ReasonCode = append(b.resource.ReasonCode, v)
	b.fieldsSet["reasonCode"] = true
	return b
}

// WithReasonReference adds an item to the reasonReference field.
func (b *MedicationRequestBuilder) WithReasonReference(v dt.Reference) *MedicationRequestBuilder {
	b.resource.ReasonReference = append(b.resource.ReasonReference, v)
	b.fieldsSet["reasonReference"] = true
	return b
}

// WithRecorder sets the recorder field.
func (b *MedicationRequestBuilder) WithRecorder(v dt.Reference) *MedicationRequestBuilder {
	b.resource.Recorder = &v
	b.fieldsSet["recorder"] = true
	return b
}

// WithReportedBoolean sets the reportedBoolean polymorphic field.
func (b *MedicationRequestBuilder) WithReportedBoolean(v bool) *MedicationRequestBuilder {
	if b.resource.Reported == nil {
		b.resource.Reported = &MedicationRequestReported{}
	}
	b.resource.Reported.Boolean = &v
	b.fieldsSet["reported"] = true
	return b
}

// WithReportedReference sets the reportedReference polymorphic field.
func (b *MedicationRequestBuilder) WithReportedReference(v dt.Reference) *MedicationRequestBuilder {
	if b.resource.Reported == nil {
		b.resource.Reported = &MedicationRequestReported{}
	}
	b.resource.Reported.Reference = &v
	b.fieldsSet["reported"] = true
	return b
}

// WithRequester sets the requester field.
func (b *MedicationRequestBuilder) WithRequester(v dt.Reference) *MedicationRequestBuilder {
	b.resource.Requester = &v
	b.fieldsSet["requester"] = true
	return b
}

// WithStatusReason sets the statusReason field.
func (b *MedicationRequestBuilder) WithStatusReason(v dt.CodeableConcept) *MedicationRequestBuilder {
	b.resource.StatusReason = &v
	b.fieldsSet["statusReason"] = true
	return b
}

// WithSubstitution sets the substitution field.
func (b *MedicationRequestBuilder) WithSubstitution(v MedicationRequestSubstitution) *MedicationRequestBuilder {
	b.resource.Substitution = &v
	b.fieldsSet["substitution"] = true
	return b
}

// WithSupportingInformation adds an item to the supportingInformation field.
func (b *MedicationRequestBuilder) WithSupportingInformation(v dt.Reference) *MedicationRequestBuilder {
	b.resource.SupportingInformation = append(b.resource.SupportingInformation, v)
	b.fieldsSet["supportingInformation"] = true
	return b
}

// Build returns the constructed MedicationRequest. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *MedicationRequestBuilder) Build() (*MedicationRequest, error) {
	var missing []string
	if !b.fieldsSet["subject"] {
		missing = append(missing, "subject")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("MedicationRequest: required fields missing: %v", missing)
	}
	r := b.resource
	return &r, nil
}

// MedicationRequestDispenseRequest An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPresc...
type MedicationRequestDispenseRequest struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// DispenseInterval The minimum period of time that must occur between dispenses of the medication.
	DispenseInterval *dt.Duration `json:"dispenseInterval,omitempty"`
	// ExpectedSupplyDuration Identifies the period time over which the supplied product is expected to be used, or the length of time the dispense is expected to last.
	ExpectedSupplyDuration *dt.Duration `json:"expectedSupplyDuration,omitempty"`
	// InitialFill Indicates the quantity or duration for the first dispense of the medication.
	InitialFill *MedicationRequestInitialFill `json:"initialFill,omitempty"`
	// NumberOfRepeatsAllowed An integer indicating the number of times, in addition to the original dispense, (aka refills or repeats) that the patient can receive the prescribed medication. Usage Notes: This integer does not ...
	NumberOfRepeatsAllowed *uint32 `json:"numberOfRepeatsAllowed,omitempty"`
	// NumberOfRepeatsAllowedElement contains element extensions for numberOfRepeatsAllowed.
	NumberOfRepeatsAllowedElement *dt.Element `json:"_numberOfRepeatsAllowed,omitempty"`
	// Performer Indicates the intended dispensing Organization specified by the prescriber.
	Performer *dt.Reference `json:"performer,omitempty"`
	// Quantity The amount that is to be dispensed for one fill.
	Quantity *dt.Quantity `json:"quantity,omitempty"`
	// ValidityPeriod This indicates the validity period of a prescription (stale dating the Prescription).
	ValidityPeriod *dt.Period `json:"validityPeriod,omitempty"`
}

// MedicationRequestInitialFill An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPresc...
type MedicationRequestInitialFill struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Duration The length of time that the first dispense is expected to last.
	Duration *dt.Duration `json:"duration,omitempty"`
	// Quantity The amount or quantity to provide as part of the first dispense.
	Quantity *dt.Quantity `json:"quantity,omitempty"`
}

// MedicationRequestSubstitution An order or request for both supply of the medication and the instructions for administration of the medication to a patient. The resource is called "MedicationRequest" rather than "MedicationPresc...
type MedicationRequestSubstitution struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Allowed True if the prescriber allows a different drug to be dispensed from what was prescribed.
	Allowed *MedicationRequestSubstitutionAllowed `json:"-"` // polymorphic
	// Reason Indicates the reason for the substitution, or why substitution must or must not be performed.
	Reason *dt.CodeableConcept `json:"reason,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for MedicationRequestSubstitution.
func (r MedicationRequestSubstitution) MarshalJSON() ([]byte, error) {
	type Alias MedicationRequestSubstitution
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Allowed != nil {
		vData, err := json.Marshal(r.Allowed)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationRequestSubstitution.
func (r *MedicationRequestSubstitution) UnmarshalJSON(data []byte) error {
	type Alias MedicationRequestSubstitution
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicationRequestSubstitution(alias)
	var allowedVal MedicationRequestSubstitutionAllowed
	if err := allowedVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if allowedVal.Boolean != nil || allowedVal.CodeableConcept != nil {
		r.Allowed = &allowedVal
	}
	return nil
}

// MedicationRequestSubstitutionAllowed represents a polymorphic choice type in FHIR.
type MedicationRequestSubstitutionAllowed struct {
	Boolean         *bool               `json:"allowedBoolean,omitempty"`         // True if the prescriber allows a different drug to be dispensed from what was prescribed.
	CodeableConcept *dt.CodeableConcept `json:"allowedCodeableConcept,omitempty"` // True if the prescriber allows a different drug to be dispensed from what was prescribed.
}

// MarshalJSON implements the json.Marshaler interface for MedicationRequestSubstitutionAllowed.
func (v MedicationRequestSubstitutionAllowed) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.Boolean != nil {
		m["allowedBoolean"] = v.Boolean
	}
	if v.CodeableConcept != nil {
		m["allowedCodeableConcept"] = v.CodeableConcept
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationRequestSubstitutionAllowed.
func (v *MedicationRequestSubstitutionAllowed) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["allowedBoolean"]; ok {
		var val bool
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling allowedBoolean: %w", err)
		}
		v.Boolean = &val
	}
	if d, ok := raw["allowedCodeableConcept"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling allowedCodeableConcept: %w", err)
		}
		v.CodeableConcept = &val
	}
	return nil
}

// MedicationRequestMedication represents a polymorphic choice type in FHIR.
type MedicationRequestMedication struct {
	CodeableConcept *dt.CodeableConcept `json:"medicationCodeableConcept,omitempty"` // Identifies the medication being requested. This is a link to a resource that represents the medication which may be the details of the medication or simply an attribute carrying a code that identif...
	Reference       *dt.Reference       `json:"medicationReference,omitempty"`       // Identifies the medication being requested. This is a link to a resource that represents the medication which may be the details of the medication or simply an attribute carrying a code that identif...
}

// MarshalJSON implements the json.Marshaler interface for MedicationRequestMedication.
func (v MedicationRequestMedication) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.CodeableConcept != nil {
		m["medicationCodeableConcept"] = v.CodeableConcept
	}
	if v.Reference != nil {
		m["medicationReference"] = v.Reference
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationRequestMedication.
func (v *MedicationRequestMedication) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["medicationCodeableConcept"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationCodeableConcept: %w", err)
		}
		v.CodeableConcept = &val
	}
	if d, ok := raw["medicationReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationReference: %w", err)
		}
		v.Reference = &val
	}
	return nil
}

// MedicationRequestReported represents a polymorphic choice type in FHIR.
type MedicationRequestReported struct {
	Boolean   *bool         `json:"reportedBoolean,omitempty"`   // Indicates if this record was captured as a secondary 'reported' record rather than as an original primary source-of-truth record.  It may also indicate the source of the report.
	Reference *dt.Reference `json:"reportedReference,omitempty"` // Indicates if this record was captured as a secondary 'reported' record rather than as an original primary source-of-truth record.  It may also indicate the source of the report.
}

// MarshalJSON implements the json.Marshaler interface for MedicationRequestReported.
func (v MedicationRequestReported) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.Boolean != nil {
		m["reportedBoolean"] = v.Boolean
	}
	if v.Reference != nil {
		m["reportedReference"] = v.Reference
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationRequestReported.
func (v *MedicationRequestReported) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["reportedBoolean"]; ok {
		var val bool
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling reportedBoolean: %w", err)
		}
		v.Boolean = &val
	}
	if d, ok := raw["reportedReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling reportedReference: %w", err)
		}
		v.Reference = &val
	}
	return nil
}
