// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// MedicinalProductPackaged A medicinal product in a container or package.
type MedicinalProductPackaged struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "MedicinalProductPackaged"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Unique identifier.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// BatchIdentifier Batch numbering.
	BatchIdentifier []MedicinalProductPackagedBatchIdentifier `json:"batchIdentifier,omitempty"`
	// Description Textual description.
	Description *string `json:"description,omitempty"`
	// DescriptionElement contains element extensions for description.
	DescriptionElement *dt.Element `json:"_description,omitempty"`
	// LegalStatusOfSupply The legal status of supply of the medicinal product as classified by the regulator.
	LegalStatusOfSupply *dt.CodeableConcept `json:"legalStatusOfSupply,omitempty"`
	// Manufacturer Manufacturer of this Package Item.
	Manufacturer []dt.Reference `json:"manufacturer,omitempty"`
	// MarketingAuthorization Manufacturer of this Package Item.
	MarketingAuthorization *dt.Reference `json:"marketingAuthorization,omitempty"`
	// MarketingStatus Marketing information.
	MarketingStatus []dt.MarketingStatus `json:"marketingStatus,omitempty"`
	// PackageItem A packaging item, as a contained for medicine, possibly with other packaging items within.
	PackageItem []MedicinalProductPackagedPackageItem `json:"packageItem,omitempty"`
	// Subject The product with this is a pack for.
	Subject []dt.Reference `json:"subject,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for MedicinalProductPackaged.
func (r MedicinalProductPackaged) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicinalProductPackaged"
	type Alias MedicinalProductPackaged
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	if len(r.Extra) == 0 {
		return data, nil
	}
	// Splice Extra fields into JSON output
	var extra []byte
	for k, v := range r.Extra {
		key, _ := json.Marshal(k)
		extra = append(extra, ',')
		extra = append(extra, key...)
		extra = append(extra, ':')
		extra = append(extra, v...)
	}
	// Insert before final '}'
	result := make([]byte, 0, len(data)+len(extra))
	result = append(result, data[:len(data)-1]...)
	result = append(result, extra...)
	result = append(result, '}')
	return result, nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicinalProductPackaged.
func (r *MedicinalProductPackaged) UnmarshalJSON(data []byte) error {
	type Alias MedicinalProductPackaged
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicinalProductPackaged(alias)
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_batchIdentifier", "_contained", "_description", "_extension", "_id", "_identifier", "_implicitRules", "_language", "_legalStatusOfSupply", "_manufacturer", "_marketingAuthorization", "_marketingStatus", "_meta", "_modifierExtension", "_packageItem", "_subject", "_text", "batchIdentifier", "contained", "description", "extension", "id", "identifier", "implicitRules", "language", "legalStatusOfSupply", "manufacturer", "marketingAuthorization", "marketingStatus", "meta", "modifierExtension", "packageItem", "resourceType", "subject", "text":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// MedicinalProductPackagedBuilder provides a fluent API for constructing MedicinalProductPackaged resources.
type MedicinalProductPackagedBuilder struct {
	resource  MedicinalProductPackaged
	fieldsSet map[string]bool
}

// NewMedicinalProductPackaged creates a new MedicinalProductPackagedBuilder for building a MedicinalProductPackaged resource.
func NewMedicinalProductPackaged() *MedicinalProductPackagedBuilder {
	return &MedicinalProductPackagedBuilder{resource: MedicinalProductPackaged{ResourceType: "MedicinalProductPackaged"}, fieldsSet: make(map[string]bool)}
}

// WithId sets the id field.
func (b *MedicinalProductPackagedBuilder) WithId(v dt.ID) *MedicinalProductPackagedBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *MedicinalProductPackagedBuilder) WithMeta(v dt.Meta) *MedicinalProductPackagedBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *MedicinalProductPackagedBuilder) WithImplicitRules(v dt.URI) *MedicinalProductPackagedBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *MedicinalProductPackagedBuilder) WithLanguage(v dt.Code) *MedicinalProductPackagedBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *MedicinalProductPackagedBuilder) WithText(v dt.Narrative) *MedicinalProductPackagedBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *MedicinalProductPackagedBuilder) WithContained(v json.RawMessage) *MedicinalProductPackagedBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *MedicinalProductPackagedBuilder) WithExtension(v dt.Extension) *MedicinalProductPackagedBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *MedicinalProductPackagedBuilder) WithModifierExtension(v dt.Extension) *MedicinalProductPackagedBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *MedicinalProductPackagedBuilder) WithIdentifier(v dt.Identifier) *MedicinalProductPackagedBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	b.fieldsSet["identifier"] = true
	return b
}

// WithBatchIdentifier adds an item to the batchIdentifier field.
func (b *MedicinalProductPackagedBuilder) WithBatchIdentifier(v MedicinalProductPackagedBatchIdentifier) *MedicinalProductPackagedBuilder {
	b.resource.BatchIdentifier = append(b.resource.BatchIdentifier, v)
	b.fieldsSet["batchIdentifier"] = true
	return b
}

// WithDescription sets the description field.
func (b *MedicinalProductPackagedBuilder) WithDescription(v string) *MedicinalProductPackagedBuilder {
	b.resource.Description = &v
	b.fieldsSet["description"] = true
	return b
}

// WithLegalStatusOfSupply sets the legalStatusOfSupply field.
func (b *MedicinalProductPackagedBuilder) WithLegalStatusOfSupply(v dt.CodeableConcept) *MedicinalProductPackagedBuilder {
	b.resource.LegalStatusOfSupply = &v
	b.fieldsSet["legalStatusOfSupply"] = true
	return b
}

// WithManufacturer adds an item to the manufacturer field.
func (b *MedicinalProductPackagedBuilder) WithManufacturer(v dt.Reference) *MedicinalProductPackagedBuilder {
	b.resource.Manufacturer = append(b.resource.Manufacturer, v)
	b.fieldsSet["manufacturer"] = true
	return b
}

// WithMarketingAuthorization sets the marketingAuthorization field.
func (b *MedicinalProductPackagedBuilder) WithMarketingAuthorization(v dt.Reference) *MedicinalProductPackagedBuilder {
	b.resource.MarketingAuthorization = &v
	b.fieldsSet["marketingAuthorization"] = true
	return b
}

// WithMarketingStatus adds an item to the marketingStatus field.
func (b *MedicinalProductPackagedBuilder) WithMarketingStatus(v dt.MarketingStatus) *MedicinalProductPackagedBuilder {
	b.resource.MarketingStatus = append(b.resource.MarketingStatus, v)
	b.fieldsSet["marketingStatus"] = true
	return b
}

// WithPackageItem adds an item to the packageItem field.
func (b *MedicinalProductPackagedBuilder) WithPackageItem(v MedicinalProductPackagedPackageItem) *MedicinalProductPackagedBuilder {
	b.resource.PackageItem = append(b.resource.PackageItem, v)
	b.fieldsSet["packageItem"] = true
	return b
}

// WithSubject adds an item to the subject field.
func (b *MedicinalProductPackagedBuilder) WithSubject(v dt.Reference) *MedicinalProductPackagedBuilder {
	b.resource.Subject = append(b.resource.Subject, v)
	b.fieldsSet["subject"] = true
	return b
}

// Build returns the constructed MedicinalProductPackaged. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *MedicinalProductPackagedBuilder) Build() (*MedicinalProductPackaged, error) {
	var missing []string
	if !b.fieldsSet["packageItem"] {
		missing = append(missing, "packageItem")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("MedicinalProductPackaged: required fields missing: %v", missing)
	}
	r := b.resource
	return &r, nil
}

// MedicinalProductPackagedBatchIdentifier A medicinal product in a container or package.
type MedicinalProductPackagedBatchIdentifier struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// ImmediatePackaging A number appearing on the immediate packaging (and not the outer packaging).
	ImmediatePackaging *dt.Identifier `json:"immediatePackaging,omitempty"`
	// OuterPackaging A number appearing on the outer packaging of a specific batch.
	OuterPackaging dt.Identifier `json:"outerPackaging"`
}

// MedicinalProductPackagedPackageItem A medicinal product in a container or package.
type MedicinalProductPackagedPackageItem struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Including possibly Data Carrier Identifier.
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// AlternateMaterial A possible alternate material for the packaging.
	AlternateMaterial []dt.CodeableConcept `json:"alternateMaterial,omitempty"`
	// Device A device accompanying a medicinal product.
	Device []dt.Reference `json:"device,omitempty"`
	// ManufacturedItem The manufactured item as contained in the packaged medicinal product.
	ManufacturedItem []dt.Reference `json:"manufacturedItem,omitempty"`
	// Manufacturer Manufacturer of this Package Item.
	Manufacturer []dt.Reference `json:"manufacturer,omitempty"`
	// Material Material type of the package item.
	Material []dt.CodeableConcept `json:"material,omitempty"`
	// OtherCharacteristics Other codeable characteristics.
	OtherCharacteristics []dt.CodeableConcept `json:"otherCharacteristics,omitempty"`
	// PackageItem Allows containers within containers.
	PackageItem []MedicinalProductPackagedPackageItem `json:"packageItem,omitempty"`
	// PhysicalCharacteristics Dimensions, color etc.
	PhysicalCharacteristics *dt.ProdCharacteristic `json:"physicalCharacteristics,omitempty"`
	// Quantity The quantity of this package in the medicinal product, at the current level of packaging. The outermost is always 1.
	Quantity dt.Quantity `json:"quantity"`
	// ShelfLifeStorage Shelf Life and storage information.
	ShelfLifeStorage []dt.ProductShelfLife `json:"shelfLifeStorage,omitempty"`
	// Type The physical type of the container of the medicine.
	Type dt.CodeableConcept `json:"type"`
}

// GetId returns the id field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetId() dt.ID {
	if r.Id != nil {
		return *r.Id
	}
	var zero dt.ID
	return zero
}

// GetMeta returns the meta field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetMeta() dt.Meta {
	if r.Meta != nil {
		return *r.Meta
	}
	var zero dt.Meta
	return zero
}

// GetImplicitRules returns the implicitRules field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetImplicitRules() dt.URI {
	if r.ImplicitRules != nil {
		return *r.ImplicitRules
	}
	var zero dt.URI
	return zero
}

// GetLanguage returns the language field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetLanguage() dt.Code {
	if r.Language != nil {
		return *r.Language
	}
	var zero dt.Code
	return zero
}

// GetText returns the text field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetText() dt.Narrative {
	if r.Text != nil {
		return *r.Text
	}
	var zero dt.Narrative
	return zero
}

// GetContained returns the contained field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetContained() []json.RawMessage {
	if r.Contained != nil {
		return r.Contained
	}
	return nil
}

// GetExtension returns the extension field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetExtension() []dt.Extension {
	if r.Extension != nil {
		return r.Extension
	}
	return nil
}

// GetModifierExtension returns the modifierExtension field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetModifierExtension() []dt.Extension {
	if r.ModifierExtension != nil {
		return r.ModifierExtension
	}
	return nil
}

// GetIdentifier returns the identifier field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetIdentifier() []dt.Identifier {
	if r.Identifier != nil {
		return r.Identifier
	}
	return nil
}

// GetBatchIdentifier returns the batchIdentifier field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetBatchIdentifier() []MedicinalProductPackagedBatchIdentifier {
	if r.BatchIdentifier != nil {
		return r.BatchIdentifier
	}
	return nil
}

// GetDescription returns the description field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetDescription() string {
	if r.Description != nil {
		return *r.Description
	}
	var zero string
	return zero
}

// GetLegalStatusOfSupply returns the legalStatusOfSupply field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetLegalStatusOfSupply() dt.CodeableConcept {
	if r.LegalStatusOfSupply != nil {
		return *r.LegalStatusOfSupply
	}
	var zero dt.CodeableConcept
	return zero
}

// GetManufacturer returns the manufacturer field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetManufacturer() []dt.Reference {
	if r.Manufacturer != nil {
		return r.Manufacturer
	}
	return nil
}

// GetMarketingAuthorization returns the marketingAuthorization field value, or the zero value if nil.
func (r *MedicinalProductPackaged) GetMarketingAuthorization() dt.Reference {
	if r.MarketingAuthorization != nil {
		return *r.MarketingAuthorization
	}
	var zero dt.Reference
	return zero
}

// GetMarketingStatus returns the marketingStatus field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetMarketingStatus() []dt.MarketingStatus {
	if r.MarketingStatus != nil {
		return r.MarketingStatus
	}
	return nil
}

// GetPackageItem returns the packageItem field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetPackageItem() []MedicinalProductPackagedPackageItem {
	if r.PackageItem != nil {
		return r.PackageItem
	}
	return nil
}

// GetSubject returns the subject field value, or an empty slice if nil.
func (r *MedicinalProductPackaged) GetSubject() []dt.Reference {
	if r.Subject != nil {
		return r.Subject
	}
	return nil
}

// GetResourceType returns the FHIR resource type name.
func (r *MedicinalProductPackaged) GetResourceType() string {
	return "MedicinalProductPackaged"
}

// GetExtra returns unknown fields captured during JSON unmarshaling.
func (r *MedicinalProductPackaged) GetExtra() map[string]json.RawMessage {
	return r.Extra
}
