// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/helixfhir/gofhir/r4/datatypes"
)

// MedicationAdministration Describes the event of a patient consuming or otherwise being administered a medication.  This may be as simple as swallowing a tablet or it may be a long running infusion.  Related resources tie t...
type MedicationAdministration struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "MedicationAdministration"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Identifier Identifiers associated with this Medication Administration that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. T...
	Identifier []dt.Identifier `json:"identifier,omitempty"`
	// Status Will generally be set to show that the administration has been completed.  For some long running administrations such as infusions, it is possible for an administration to be started but not comple...
	Status *dt.Code `json:"status,omitempty"`
	// Category Indicates where the medication is expected to be consumed or administered.
	Category *dt.CodeableConcept `json:"category,omitempty"`
	// Context The visit, admission, or other contact between patient and health care provider during which the medication administration was performed.
	Context *dt.Reference `json:"context,omitempty"`
	// Device The device used in administering the medication to the patient.  For example, a particular infusion pump.
	Device []dt.Reference `json:"device,omitempty"`
	// Dosage Describes the medication dosage information details e.g. dose, rate, site, route, etc.
	Dosage *MedicationAdministrationDosage `json:"dosage,omitempty"`
	// Effective A specific date/time or interval of time during which the administration took place (or did not take place, when the 'notGiven' attribute is true). For many administrations, such as swallowing a ta...
	Effective *MedicationAdministrationEffective `json:"-"` // polymorphic
	// EventHistory A summary of the events of interest that have occurred, such as when the administration was verified.
	EventHistory []dt.Reference `json:"eventHistory,omitempty"`
	// Instantiates A protocol, guideline, orderset, or other definition that was adhered to in whole or in part by this event.
	Instantiates []dt.URI `json:"instantiates,omitempty"`
	// Medication Identifies the medication that was administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication ...
	Medication *MedicationAdministrationMedication `json:"-"` // polymorphic
	// Note Extra information about the medication administration that is not conveyed by the other attributes.
	Note []dt.Annotation `json:"note,omitempty"`
	// PartOf A larger event of which this particular event is a component or step.
	PartOf []dt.Reference `json:"partOf,omitempty"`
	// Performer Indicates who or what performed the medication administration and how they were involved.
	Performer []MedicationAdministrationPerformer `json:"performer,omitempty"`
	// ReasonCode A code indicating why the medication was given.
	ReasonCode []dt.CodeableConcept `json:"reasonCode,omitempty"`
	// ReasonReference Condition or observation that supports why the medication was administered.
	ReasonReference []dt.Reference `json:"reasonReference,omitempty"`
	// Request The original request, instruction or authority to perform the administration.
	Request *dt.Reference `json:"request,omitempty"`
	// StatusReason A code indicating why the administration was not performed.
	StatusReason []dt.CodeableConcept `json:"statusReason,omitempty"`
	// Subject The person or animal or group receiving the medication.
	Subject dt.Reference `json:"subject"`
	// SupportingInformation Additional information (for example, patient height and weight) that supports the administration of the medication.
	SupportingInformation []dt.Reference `json:"supportingInformation,omitempty"`
}

// MarshalJSON implements the json.Marshaler interface for MedicationAdministration.
func (r MedicationAdministration) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicationAdministration"
	type Alias MedicationAdministration
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	// Merge polymorphic fields into the JSON object
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Effective != nil {
		vData, err := json.Marshal(r.Effective)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	if r.Medication != nil {
		vData, err := json.Marshal(r.Medication)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationAdministration.
func (r *MedicationAdministration) UnmarshalJSON(data []byte) error {
	type Alias MedicationAdministration
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicationAdministration(alias)
	// Unmarshal polymorphic fields
	var medicationVal MedicationAdministrationMedication
	if err := medicationVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if medicationVal.CodeableConcept != nil || medicationVal.Reference != nil {
		r.Medication = &medicationVal
	}
	var effectiveVal MedicationAdministrationEffective
	if err := effectiveVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if effectiveVal.DateTime != nil || effectiveVal.Period != nil {
		r.Effective = &effectiveVal
	}
	return nil
}

// MedicationAdministrationBuilder provides a fluent API for constructing MedicationAdministration resources.
type MedicationAdministrationBuilder struct {
	resource MedicationAdministration
}

// NewMedicationAdministration creates a new MedicationAdministrationBuilder for building a MedicationAdministration resource.
func NewMedicationAdministration() *MedicationAdministrationBuilder {
	return &MedicationAdministrationBuilder{resource: MedicationAdministration{ResourceType: "MedicationAdministration"}}
}

// WithId sets the id field.
func (b *MedicationAdministrationBuilder) WithId(v dt.ID) *MedicationAdministrationBuilder {
	b.resource.Id = &v
	return b
}

// WithMeta sets the meta field.
func (b *MedicationAdministrationBuilder) WithMeta(v dt.Meta) *MedicationAdministrationBuilder {
	b.resource.Meta = &v
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *MedicationAdministrationBuilder) WithImplicitRules(v dt.URI) *MedicationAdministrationBuilder {
	b.resource.ImplicitRules = &v
	return b
}

// WithLanguage sets the language field.
func (b *MedicationAdministrationBuilder) WithLanguage(v dt.Code) *MedicationAdministrationBuilder {
	b.resource.Language = &v
	return b
}

// WithText sets the text field.
func (b *MedicationAdministrationBuilder) WithText(v dt.Narrative) *MedicationAdministrationBuilder {
	b.resource.Text = &v
	return b
}

// WithContained adds an item to the contained field.
func (b *MedicationAdministrationBuilder) WithContained(v json.RawMessage) *MedicationAdministrationBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	return b
}

// WithExtension adds an item to the extension field.
func (b *MedicationAdministrationBuilder) WithExtension(v dt.Extension) *MedicationAdministrationBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *MedicationAdministrationBuilder) WithModifierExtension(v dt.Extension) *MedicationAdministrationBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	return b
}

// WithIdentifier adds an item to the identifier field.
func (b *MedicationAdministrationBuilder) WithIdentifier(v dt.Identifier) *MedicationAdministrationBuilder {
	b.resource.Identifier = append(b.resource.Identifier, v)
	return b
}

// WithStatus sets the status field.
func (b *MedicationAdministrationBuilder) WithStatus(v dt.Code) *MedicationAdministrationBuilder {
	b.resource.Status = &v
	return b
}

// WithCategory sets the category field.
func (b *MedicationAdministrationBuilder) WithCategory(v dt.CodeableConcept) *MedicationAdministrationBuilder {
	b.resource.Category = &v
	return b
}

// WithContext sets the context field.
func (b *MedicationAdministrationBuilder) WithContext(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.Context = &v
	return b
}

// WithDevice adds an item to the device field.
func (b *MedicationAdministrationBuilder) WithDevice(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.Device = append(b.resource.Device, v)
	return b
}

// WithDosage sets the dosage field.
func (b *MedicationAdministrationBuilder) WithDosage(v MedicationAdministrationDosage) *MedicationAdministrationBuilder {
	b.resource.Dosage = &v
	return b
}

// WithEffectiveDateTime sets the effectiveDateTime polymorphic field.
func (b *MedicationAdministrationBuilder) WithEffectiveDateTime(v string) *MedicationAdministrationBuilder {
	if b.resource.Effective == nil {
		b.resource.Effective = &MedicationAdministrationEffective{}
	}
	b.resource.Effective.DateTime = &v
	return b
}

// WithEffectivePeriod sets the effectivePeriod polymorphic field.
func (b *MedicationAdministrationBuilder) WithEffectivePeriod(v dt.Period) *MedicationAdministrationBuilder {
	if b.resource.Effective == nil {
		b.resource.Effective = &MedicationAdministrationEffective{}
	}
	b.resource.Effective.Period = &v
	return b
}

// WithEventHistory adds an item to the eventHistory field.
func (b *MedicationAdministrationBuilder) WithEventHistory(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.EventHistory = append(b.resource.EventHistory, v)
	return b
}

// WithInstantiates adds an item to the instantiates field.
func (b *MedicationAdministrationBuilder) WithInstantiates(v dt.URI) *MedicationAdministrationBuilder {
	b.resource.Instantiates = append(b.resource.Instantiates, v)
	return b
}

// WithMedicationCodeableConcept sets the medicationCodeableConcept polymorphic field.
func (b *MedicationAdministrationBuilder) WithMedicationCodeableConcept(v dt.CodeableConcept) *MedicationAdministrationBuilder {
	if b.resource.Medication == nil {
		b.resource.Medication = &MedicationAdministrationMedication{}
	}
	b.resource.Medication.CodeableConcept = &v
	return b
}

// WithMedicationReference sets the medicationReference polymorphic field.
func (b *MedicationAdministrationBuilder) WithMedicationReference(v dt.Reference) *MedicationAdministrationBuilder {
	if b.resource.Medication == nil {
		b.resource.Medication = &MedicationAdministrationMedication{}
	}
	b.resource.Medication.Reference = &v
	return b
}

// WithNote adds an item to the note field.
func (b *MedicationAdministrationBuilder) WithNote(v dt.Annotation) *MedicationAdministrationBuilder {
	b.resource.Note = append(b.resource.Note, v)
	return b
}

// WithPartOf adds an item to the partOf field.
func (b *MedicationAdministrationBuilder) WithPartOf(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.PartOf = append(b.resource.PartOf, v)
	return b
}

// WithPerformer adds an item to the performer field.
func (b *MedicationAdministrationBuilder) WithPerformer(v MedicationAdministrationPerformer) *MedicationAdministrationBuilder {
	b.resource.Performer = append(b.resource.Performer, v)
	return b
}

// WithReasonCode adds an item to the reasonCode field.
func (b *MedicationAdministrationBuilder) WithReasonCode(v dt.CodeableConcept) *MedicationAdministrationBuilder {
	b.resource.ReasonCode = append(b.resource.ReasonCode, v)
	return b
}

// WithReasonReference adds an item to the reasonReference field.
func (b *MedicationAdministrationBuilder) WithReasonReference(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.ReasonReference = append(b.resource.ReasonReference, v)
	return b
}

// WithRequest sets the request field.
func (b *MedicationAdministrationBuilder) WithRequest(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.Request = &v
	return b
}

// WithStatusReason adds an item to the statusReason field.
func (b *MedicationAdministrationBuilder) WithStatusReason(v dt.CodeableConcept) *MedicationAdministrationBuilder {
	b.resource.StatusReason = append(b.resource.StatusReason, v)
	return b
}

// WithSubject sets the subject field.
func (b *MedicationAdministrationBuilder) WithSubject(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.Subject = v
	return b
}

// WithSupportingInformation adds an item to the supportingInformation field.
func (b *MedicationAdministrationBuilder) WithSupportingInformation(v dt.Reference) *MedicationAdministrationBuilder {
	b.resource.SupportingInformation = append(b.resource.SupportingInformation, v)
	return b
}

// Build returns the constructed MedicationAdministration. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *MedicationAdministrationBuilder) Build() (*MedicationAdministration, error) {
	r := b.resource
	return &r, nil
}

// MedicationAdministrationDosage Describes the event of a patient consuming or otherwise being administered a medication.  This may be as simple as swallowing a tablet or it may be a long running infusion.  Related resources tie t...
type MedicationAdministrationDosage struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Text Free text dosage can be used for cases where the dosage administered is too complex to code. When coded dosage is present, the free text dosage may still be present for display to humans.The dosage...
	Text *string `json:"text,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Dose The amount of the medication given at one administration event.   Use this value when the administration is essentially an instantaneous event such as a swallowing a tablet or giving an injection.
	Dose *dt.Quantity `json:"dose,omitempty"`
	// Method A coded value indicating the method by which the medication is intended to be or was introduced into or on the body.  This attribute will most often NOT be populated.  It is most commonly used for ...
	Method *dt.CodeableConcept `json:"method,omitempty"`
	// Rate Identifies the speed with which the medication was or will be introduced into the patient.  Typically, the rate for an infusion e.g. 100 ml per 1 hour or 100 ml/hr.  May also be expressed as a rate...
	Rate *MedicationAdministrationDosageRate `json:"-"` // polymorphic
	// Route A code specifying the route or physiological path of administration of a therapeutic agent into or onto the patient.  For example, topical, intravenous, etc.
	Route *dt.CodeableConcept `json:"route,omitempty"`
	// Site A coded specification of the anatomic site where the medication first entered the body.  For example, "left arm".
	Site *dt.CodeableConcept `json:"site,omitempty"`
}

// MedicationAdministrationDosageRate represents a polymorphic choice type in FHIR.
type MedicationAdministrationDosageRate struct {
	Quantity *dt.Quantity `json:"rateQuantity,omitempty"` // Identifies the speed with which the medication was or will be introduced into the patient.  Typically, the rate for an infusion e.g. 100 ml per 1 hour or 100 ml/hr.  May also be expressed as a rate...
	Ratio    *dt.Ratio    `json:"rateRatio,omitempty"`    // Identifies the speed with which the medication was or will be introduced into the patient.  Typically, the rate for an infusion e.g. 100 ml per 1 hour or 100 ml/hr.  May also be expressed as a rate...
}

// MarshalJSON implements the json.Marshaler interface for MedicationAdministrationDosageRate.
func (v MedicationAdministrationDosageRate) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.Quantity != nil {
		m["rateQuantity"] = v.Quantity
	}
	if v.Ratio != nil {
		m["rateRatio"] = v.Ratio
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationAdministrationDosageRate.
func (v *MedicationAdministrationDosageRate) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["rateQuantity"]; ok {
		var val dt.Quantity
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling rateQuantity: %w", err)
		}
		v.Quantity = &val
	}
	if d, ok := raw["rateRatio"]; ok {
		var val dt.Ratio
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling rateRatio: %w", err)
		}
		v.Ratio = &val
	}
	return nil
}

// MedicationAdministrationPerformer Describes the event of a patient consuming or otherwise being administered a medication.  This may be as simple as swallowing a tablet or it may be a long running infusion.  Related resources tie t...
type MedicationAdministrationPerformer struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Actor Indicates who or what performed the medication administration.
	Actor dt.Reference `json:"actor"`
	// Function Distinguishes the type of involvement of the performer in the medication administration.
	Function *dt.CodeableConcept `json:"function,omitempty"`
}

// MedicationAdministrationEffective represents a polymorphic choice type in FHIR.
type MedicationAdministrationEffective struct {
	DateTime *string    `json:"effectiveDateTime,omitempty"` // A specific date/time or interval of time during which the administration took place (or did not take place, when the 'notGiven' attribute is true). For many administrations, such as swallowing a ta...
	Period   *dt.Period `json:"effectivePeriod,omitempty"`   // A specific date/time or interval of time during which the administration took place (or did not take place, when the 'notGiven' attribute is true). For many administrations, such as swallowing a ta...
}

// MarshalJSON implements the json.Marshaler interface for MedicationAdministrationEffective.
func (v MedicationAdministrationEffective) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.DateTime != nil {
		m["effectiveDateTime"] = v.DateTime
	}
	if v.Period != nil {
		m["effectivePeriod"] = v.Period
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationAdministrationEffective.
func (v *MedicationAdministrationEffective) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["effectiveDateTime"]; ok {
		var val string
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling effectiveDateTime: %w", err)
		}
		v.DateTime = &val
	}
	if d, ok := raw["effectivePeriod"]; ok {
		var val dt.Period
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling effectivePeriod: %w", err)
		}
		v.Period = &val
	}
	return nil
}

// MedicationAdministrationMedication represents a polymorphic choice type in FHIR.
type MedicationAdministrationMedication struct {
	CodeableConcept *dt.CodeableConcept `json:"medicationCodeableConcept,omitempty"` // Identifies the medication that was administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication ...
	Reference       *dt.Reference       `json:"medicationReference,omitempty"`       // Identifies the medication that was administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication ...
}

// MarshalJSON implements the json.Marshaler interface for MedicationAdministrationMedication.
func (v MedicationAdministrationMedication) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.CodeableConcept != nil {
		m["medicationCodeableConcept"] = v.CodeableConcept
	}
	if v.Reference != nil {
		m["medicationReference"] = v.Reference
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicationAdministrationMedication.
func (v *MedicationAdministrationMedication) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["medicationCodeableConcept"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationCodeableConcept: %w", err)
		}
		v.CodeableConcept = &val
	}
	if d, ok := raw["medicationReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationReference: %w", err)
		}
		v.Reference = &val
	}
	return nil
}
