// Copyright 2026 the gofhir Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by cmd/gen from the FHIR R4 specification. DO NOT EDIT.

package resources

import (
	"encoding/json"
	"fmt"

	dt "github.com/caucehealth/gofhir/r4/datatypes"
)

// MedicinalProductContraindication The clinical particulars - indications, contraindications etc. of a medicinal product, including for regulatory purposes.
type MedicinalProductContraindication struct {
	// ResourceType is the FHIR resource type name.
	ResourceType string `json:"resourceType"` // Always "MedicinalProductContraindication"
	// Id The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
	Id *dt.ID `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Meta The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.
	Meta *dt.Meta `json:"meta,omitempty"`
	// ImplicitRules A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide t...
	ImplicitRules *dt.URI `json:"implicitRules,omitempty"`
	// ImplicitRulesElement contains element extensions for implicitRules.
	ImplicitRulesElement *dt.Element `json:"_implicitRules,omitempty"`
	// Language The base language in which the resource is written.
	Language *dt.Code `json:"language,omitempty"`
	// LanguageElement contains element extensions for language.
	LanguageElement *dt.Element `json:"_language,omitempty"`
	// Text A human-readable narrative that contains a summary of the resource and can be used to represent the content of the resource to a human. The narrative need not encode all the structured data, but is...
	Text *dt.Narrative `json:"text,omitempty"`
	// Contained These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, and nor can they have their own independent transaction sc...
	Contained []json.RawMessage `json:"contained,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  app...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Comorbidity A comorbidity (concurrent condition) or coinfection.
	Comorbidity []dt.CodeableConcept `json:"comorbidity,omitempty"`
	// Disease The disease, symptom or procedure for the contraindication.
	Disease *dt.CodeableConcept `json:"disease,omitempty"`
	// DiseaseStatus The status of the disease or symptom for the contraindication.
	DiseaseStatus *dt.CodeableConcept `json:"diseaseStatus,omitempty"`
	// OtherTherapy Information about the use of the medicinal product in relation to other therapies described as part of the indication.
	OtherTherapy []MedicinalProductContraindicationOtherTherapy `json:"otherTherapy,omitempty"`
	// Population The population group to which this applies.
	Population []dt.Population `json:"population,omitempty"`
	// Subject The medication for which this is an indication.
	Subject []dt.Reference `json:"subject,omitempty"`
	// TherapeuticIndication Information about the use of the medicinal product in relation to other therapies as part of the indication.
	TherapeuticIndication []dt.Reference `json:"therapeuticIndication,omitempty"`
	// Extra contains any JSON fields not recognized by this resource type.
	Extra map[string]json.RawMessage `json:"-"`
}

// MarshalJSON implements the json.Marshaler interface for MedicinalProductContraindication.
func (r MedicinalProductContraindication) MarshalJSON() ([]byte, error) {
	r.ResourceType = "MedicinalProductContraindication"
	type Alias MedicinalProductContraindication
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	if len(r.Extra) == 0 {
		return data, nil
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	for k, v := range r.Extra {
		m[k] = v
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicinalProductContraindication.
func (r *MedicinalProductContraindication) UnmarshalJSON(data []byte) error {
	type Alias MedicinalProductContraindication
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicinalProductContraindication(alias)
	// Capture unknown fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for k, v := range raw {
		switch k {
		case "_comorbidity", "_contained", "_disease", "_diseaseStatus", "_extension", "_id", "_implicitRules", "_language", "_meta", "_modifierExtension", "_otherTherapy", "_population", "_subject", "_text", "_therapeuticIndication", "comorbidity", "contained", "disease", "diseaseStatus", "extension", "id", "implicitRules", "language", "meta", "modifierExtension", "otherTherapy", "population", "resourceType", "subject", "text", "therapeuticIndication":
			// known field
		default:
			if r.Extra == nil {
				r.Extra = make(map[string]json.RawMessage)
			}
			r.Extra[k] = v
		}
	}
	return nil
}

// MedicinalProductContraindicationBuilder provides a fluent API for constructing MedicinalProductContraindication resources.
type MedicinalProductContraindicationBuilder struct {
	resource  MedicinalProductContraindication
	fieldsSet map[string]bool
}

// NewMedicinalProductContraindication creates a new MedicinalProductContraindicationBuilder for building a MedicinalProductContraindication resource.
func NewMedicinalProductContraindication() *MedicinalProductContraindicationBuilder {
	return &MedicinalProductContraindicationBuilder{resource: MedicinalProductContraindication{ResourceType: "MedicinalProductContraindication"}, fieldsSet: make(map[string]bool)}
}

// WithId sets the id field.
func (b *MedicinalProductContraindicationBuilder) WithId(v dt.ID) *MedicinalProductContraindicationBuilder {
	b.resource.Id = &v
	b.fieldsSet["id"] = true
	return b
}

// WithMeta sets the meta field.
func (b *MedicinalProductContraindicationBuilder) WithMeta(v dt.Meta) *MedicinalProductContraindicationBuilder {
	b.resource.Meta = &v
	b.fieldsSet["meta"] = true
	return b
}

// WithImplicitRules sets the implicitRules field.
func (b *MedicinalProductContraindicationBuilder) WithImplicitRules(v dt.URI) *MedicinalProductContraindicationBuilder {
	b.resource.ImplicitRules = &v
	b.fieldsSet["implicitRules"] = true
	return b
}

// WithLanguage sets the language field.
func (b *MedicinalProductContraindicationBuilder) WithLanguage(v dt.Code) *MedicinalProductContraindicationBuilder {
	b.resource.Language = &v
	b.fieldsSet["language"] = true
	return b
}

// WithText sets the text field.
func (b *MedicinalProductContraindicationBuilder) WithText(v dt.Narrative) *MedicinalProductContraindicationBuilder {
	b.resource.Text = &v
	b.fieldsSet["text"] = true
	return b
}

// WithContained adds an item to the contained field.
func (b *MedicinalProductContraindicationBuilder) WithContained(v json.RawMessage) *MedicinalProductContraindicationBuilder {
	b.resource.Contained = append(b.resource.Contained, v)
	b.fieldsSet["contained"] = true
	return b
}

// WithExtension adds an item to the extension field.
func (b *MedicinalProductContraindicationBuilder) WithExtension(v dt.Extension) *MedicinalProductContraindicationBuilder {
	b.resource.Extension = append(b.resource.Extension, v)
	b.fieldsSet["extension"] = true
	return b
}

// WithModifierExtension adds an item to the modifierExtension field.
func (b *MedicinalProductContraindicationBuilder) WithModifierExtension(v dt.Extension) *MedicinalProductContraindicationBuilder {
	b.resource.ModifierExtension = append(b.resource.ModifierExtension, v)
	b.fieldsSet["modifierExtension"] = true
	return b
}

// WithComorbidity adds an item to the comorbidity field.
func (b *MedicinalProductContraindicationBuilder) WithComorbidity(v dt.CodeableConcept) *MedicinalProductContraindicationBuilder {
	b.resource.Comorbidity = append(b.resource.Comorbidity, v)
	b.fieldsSet["comorbidity"] = true
	return b
}

// WithDisease sets the disease field.
func (b *MedicinalProductContraindicationBuilder) WithDisease(v dt.CodeableConcept) *MedicinalProductContraindicationBuilder {
	b.resource.Disease = &v
	b.fieldsSet["disease"] = true
	return b
}

// WithDiseaseStatus sets the diseaseStatus field.
func (b *MedicinalProductContraindicationBuilder) WithDiseaseStatus(v dt.CodeableConcept) *MedicinalProductContraindicationBuilder {
	b.resource.DiseaseStatus = &v
	b.fieldsSet["diseaseStatus"] = true
	return b
}

// WithOtherTherapy adds an item to the otherTherapy field.
func (b *MedicinalProductContraindicationBuilder) WithOtherTherapy(v MedicinalProductContraindicationOtherTherapy) *MedicinalProductContraindicationBuilder {
	b.resource.OtherTherapy = append(b.resource.OtherTherapy, v)
	b.fieldsSet["otherTherapy"] = true
	return b
}

// WithPopulation adds an item to the population field.
func (b *MedicinalProductContraindicationBuilder) WithPopulation(v dt.Population) *MedicinalProductContraindicationBuilder {
	b.resource.Population = append(b.resource.Population, v)
	b.fieldsSet["population"] = true
	return b
}

// WithSubject adds an item to the subject field.
func (b *MedicinalProductContraindicationBuilder) WithSubject(v dt.Reference) *MedicinalProductContraindicationBuilder {
	b.resource.Subject = append(b.resource.Subject, v)
	b.fieldsSet["subject"] = true
	return b
}

// WithTherapeuticIndication adds an item to the therapeuticIndication field.
func (b *MedicinalProductContraindicationBuilder) WithTherapeuticIndication(v dt.Reference) *MedicinalProductContraindicationBuilder {
	b.resource.TherapeuticIndication = append(b.resource.TherapeuticIndication, v)
	b.fieldsSet["therapeuticIndication"] = true
	return b
}

// Build returns the constructed MedicinalProductContraindication. It returns an error if any required
// field (cardinality 1..1) is not set.
func (b *MedicinalProductContraindicationBuilder) Build() (*MedicinalProductContraindication, error) {
	r := b.resource
	return &r, nil
}

// MedicinalProductContraindicationOtherTherapy The clinical particulars - indications, contraindications etc. of a medicinal product, including for regulatory purposes.
type MedicinalProductContraindicationOtherTherapy struct {
	// Id Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
	Id *string `json:"id,omitempty"`
	// IdElement contains element extensions for id.
	IdElement *dt.Element `json:"_id,omitempty"`
	// Extension May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  appl...
	Extension []dt.Extension `json:"extension,omitempty"`
	// ModifierExtension May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the unders...
	ModifierExtension []dt.Extension `json:"modifierExtension,omitempty"`
	// Medication Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication.
	Medication *MedicinalProductContraindicationOtherTherapyMedication `json:"-"` // polymorphic
	// TherapyRelationshipType The type of relationship between the medicinal product indication or contraindication and another therapy.
	TherapyRelationshipType dt.CodeableConcept `json:"therapyRelationshipType"`
}

// MarshalJSON implements the json.Marshaler interface for MedicinalProductContraindicationOtherTherapy.
func (r MedicinalProductContraindicationOtherTherapy) MarshalJSON() ([]byte, error) {
	type Alias MedicinalProductContraindicationOtherTherapy
	data, err := json.Marshal((Alias)(r))
	if err != nil {
		return nil, err
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	if r.Medication != nil {
		vData, err := json.Marshal(r.Medication)
		if err != nil {
			return nil, err
		}
		var vm map[string]json.RawMessage
		if err := json.Unmarshal(vData, &vm); err != nil {
			return nil, err
		}
		for k, v := range vm {
			m[k] = v
		}
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicinalProductContraindicationOtherTherapy.
func (r *MedicinalProductContraindicationOtherTherapy) UnmarshalJSON(data []byte) error {
	type Alias MedicinalProductContraindicationOtherTherapy
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*r = MedicinalProductContraindicationOtherTherapy(alias)
	var medicationVal MedicinalProductContraindicationOtherTherapyMedication
	if err := medicationVal.UnmarshalJSON(data); err != nil {
		return err
	}
	if medicationVal.CodeableConcept != nil || medicationVal.Reference != nil {
		r.Medication = &medicationVal
	}
	return nil
}

// MedicinalProductContraindicationOtherTherapyMedication represents a polymorphic choice type in FHIR.
type MedicinalProductContraindicationOtherTherapyMedication struct {
	CodeableConcept *dt.CodeableConcept `json:"medicationCodeableConcept,omitempty"` // Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication.
	Reference       *dt.Reference       `json:"medicationReference,omitempty"`       // Reference to a specific medication (active substance, medicinal product or class of products) as part of an indication or contraindication.
}

// MarshalJSON implements the json.Marshaler interface for MedicinalProductContraindicationOtherTherapyMedication.
func (v MedicinalProductContraindicationOtherTherapyMedication) MarshalJSON() ([]byte, error) {
	m := make(map[string]interface{})
	if v.CodeableConcept != nil {
		m["medicationCodeableConcept"] = v.CodeableConcept
	}
	if v.Reference != nil {
		m["medicationReference"] = v.Reference
	}
	return json.Marshal(m)
}

// UnmarshalJSON implements the json.Unmarshaler interface for MedicinalProductContraindicationOtherTherapyMedication.
func (v *MedicinalProductContraindicationOtherTherapyMedication) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if d, ok := raw["medicationCodeableConcept"]; ok {
		var val dt.CodeableConcept
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationCodeableConcept: %w", err)
		}
		v.CodeableConcept = &val
	}
	if d, ok := raw["medicationReference"]; ok {
		var val dt.Reference
		if err := json.Unmarshal(d, &val); err != nil {
			return fmt.Errorf("unmarshaling medicationReference: %w", err)
		}
		v.Reference = &val
	}
	return nil
}

// GetId returns the id field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetId() dt.ID {
	if r.Id != nil {
		return *r.Id
	}
	var zero dt.ID
	return zero
}

// GetMeta returns the meta field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetMeta() dt.Meta {
	if r.Meta != nil {
		return *r.Meta
	}
	var zero dt.Meta
	return zero
}

// GetImplicitRules returns the implicitRules field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetImplicitRules() dt.URI {
	if r.ImplicitRules != nil {
		return *r.ImplicitRules
	}
	var zero dt.URI
	return zero
}

// GetLanguage returns the language field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetLanguage() dt.Code {
	if r.Language != nil {
		return *r.Language
	}
	var zero dt.Code
	return zero
}

// GetText returns the text field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetText() dt.Narrative {
	if r.Text != nil {
		return *r.Text
	}
	var zero dt.Narrative
	return zero
}

// GetContained returns the contained field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetContained() []json.RawMessage {
	if r.Contained != nil {
		return r.Contained
	}
	return nil
}

// GetExtension returns the extension field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetExtension() []dt.Extension {
	if r.Extension != nil {
		return r.Extension
	}
	return nil
}

// GetModifierExtension returns the modifierExtension field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetModifierExtension() []dt.Extension {
	if r.ModifierExtension != nil {
		return r.ModifierExtension
	}
	return nil
}

// GetComorbidity returns the comorbidity field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetComorbidity() []dt.CodeableConcept {
	if r.Comorbidity != nil {
		return r.Comorbidity
	}
	return nil
}

// GetDisease returns the disease field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetDisease() dt.CodeableConcept {
	if r.Disease != nil {
		return *r.Disease
	}
	var zero dt.CodeableConcept
	return zero
}

// GetDiseaseStatus returns the diseaseStatus field value, or the zero value if nil.
func (r *MedicinalProductContraindication) GetDiseaseStatus() dt.CodeableConcept {
	if r.DiseaseStatus != nil {
		return *r.DiseaseStatus
	}
	var zero dt.CodeableConcept
	return zero
}

// GetOtherTherapy returns the otherTherapy field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetOtherTherapy() []MedicinalProductContraindicationOtherTherapy {
	if r.OtherTherapy != nil {
		return r.OtherTherapy
	}
	return nil
}

// GetPopulation returns the population field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetPopulation() []dt.Population {
	if r.Population != nil {
		return r.Population
	}
	return nil
}

// GetSubject returns the subject field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetSubject() []dt.Reference {
	if r.Subject != nil {
		return r.Subject
	}
	return nil
}

// GetTherapeuticIndication returns the therapeuticIndication field value, or an empty slice if nil.
func (r *MedicinalProductContraindication) GetTherapeuticIndication() []dt.Reference {
	if r.TherapeuticIndication != nil {
		return r.TherapeuticIndication
	}
	return nil
}
